### ISSUE TITLE
امکان پخش اذان به صورت کامل و اذان‌های بیشتر قابل انتخاب

### ISSUE THREAD

**Issue by smtaheri** [persian-calendar/DroidPersianCalendar#157]
اضافه نمودن گزینه پخش اذان به صورت کامل یا انتخاب فایل صوتی اذان به صورت دلخواه
#enhancement

**Comment by haasanentezari** [comment]
اضافه شدن بخش کامل اذان

**Comment by ebraminio** [comment]
واقعیت، مشکل اصلی با اذان با صداهای بیشتر و بهتر نداشتن مجوز حق تکثیر برای اذانی آزاد قابل استفاده در برنامهٔ آزاد است. اثار تولید شده در ایران تا ۴۰ سال پس از مرگ مؤلف دارای حق نشر است و استفاده بی‌اجازه از صاحب (یا وارثان آن‌ها) غیر قانونی حساب می‌شود به خاطر همین از اذان موذن مصری استفاده شده که شامل قوانین آنجا شود.

**Comment by MEHDIMYADI** [comment]
خوب میتونیم کاری کنیم در بخش تنظیمات کاربر هر اذانی که دانلود کرده رو از حافظه‌ی دستگاه خودش 
انتخاب کنه که دیگه مسئله کپی‌رایت رو دوش کاربر خواهد بود.
اما دسترسی میخواد انجام بدم؟

**Comment by ebraminio** [comment]
دسترسی دردسر ایجاد می‌کند :/

**Comment by MEHDIMYADI** [comment]
چاره‌ای نیست نمیدونم نظرسنجی چیزی گذاشته بشه ببینیم عموم کاربرا چی میگن الان تمامی برنامه ها انتخاب اذان دارند به نظرم حیف هست این قسمت رو بهبود ندیم
یک اذان بسیار زیبا و ناب از مرحوم مودن زاده است کاش این رو جایگزین می کردین
http://dl.aviny.com/voice/azan/moazenin/52-salim-moazenzadeh-01.mp3
اگر دوست داشتین انجام بدین من به ogg تبدیل کردم

**Comment by ebraminio** [comment]
قسمت انتخاب اذان دلخواه توسط مهدی مدت زیادیست که انجام شده است، ممنون :)
