### ISSUE TITLE
ادغام دیالوگ‌های طول و عرض جغرفیایی و سایر در تنظیمات و ایجاد فهرست شهرها منتخب و ذخیره موقعیت

### ISSUE THREAD

**Issue by derakhshana** [persian-calendar/DroidPersianCalendar#173]
اگه میشد موقعیت را را وقتی از جی پی اس دریافت میکرد با یک اسم دلخواه ذخیره میکردیم و با تایید برای محاسبه اوقات شرعی مورد استفاده قرار میگرقت و در مراجعات بعدی فقط از لیست انتخاب میشد خوب بود

**Comment by ebraminio** [comment]
ایدهٔ درست و خیلی خوبیه

**Comment by ebraminio** [comment]
اصلاح در #651
