### ISSUE TITLE
شخصی سازی ویجت

### ISSUE THREAD

**Issue by tahmagin** [persian-calendar/DroidPersianCalendar#258]
اگه امکان شخصی سازی ویجت با قابلیت های زیر را فراهم کنید عالی میشه.
۱. امکان استفاده از فونت های شخصی
۲. امکان تغییر رنگ پس زمینه
۳. وسط چین، راست چین و چپ چین کردن
۴. تغییر اندازه نوشته

**Comment by mhosem** [comment]
بخصوص امکان وسط چین کردن، توی زیبای صفحه اول خیلی موثر هستش

**Comment by ebraminio** [comment]
وسط‌چین کردن برای نسخهٔ بعد انجام شد :)

**Comment by ebraminio** [comment]
تغییر رنگ پس‌زمینه نیز انجام شد :) وسط‌چین نیز برای آن‌هایی که ممکن است دارد، ولی تغییر اندازه کمی دردسر است فونت شخصی خیلی دردسر است (باید تصویر برایش بفرستیم) با تشکر ایشو رو می‌بندم :) ممنون
