### ISSUE TITLE
نمایش عددی روز 

### ISSUE THREAD

**Issue by fcbwin** [persian-calendar/DroidPersianCalendar#271]
سلام
لطفا در نوار اعلان بالای صفحه بجای آیکون برنامه عدد روزی که در آن قرار داریم نمایش داده شود
گوشی بنده: شیائومی

**Comment by ebraminio** [comment]
سلام! این مشکل بعضی از گوشی‌هاست که از آنجایی که شخصاً این گوشی‌ها را ندیدم که بتوانم تست کنم چگونه مشکلش را برطرف کنم راه‌حلش را نمی‌دانم

**Comment by ebraminio** [comment]
به نظر نمی‌آید از طرف ما راه‌حلی داشته باشد :/
