### ISSUE TITLE
مشکل در باز کردن رویدادهای تکراری

### ISSUE THREAD

**Issue by Rahmanism** [persian-calendar/DroidPersianCalendar#349]
سلام
وقتی نمایش رویدادهای شخصی فعاله، روی هر رویدادی که میزنم باز میشه، اما اگه رویداد از نوع تکراری باشه (مثلا رویدادی که هر هفته سه شنبه تکرار شده) خطا میده
خطای event not found.

**Comment by ebraminio** [comment]
سلام! من مشکلی نداشتم با S Planner سامسونگ

از چه برنامه‌ای استفاده می‌کنید یا گوشی‌تان چیست؟ ممنون :)

**Comment by smrahmani** [comment]
گوشی Motorola Moto Z
اپ تقویم گوگل رو استفاده میکنم.

ممنون

**Comment by ebraminio** [comment]
ظاهراً که الآن این مشکل را در تقویم گوگل ندارم، حتماً دوباره بررسی کنید و اشکال بود بفرمایید، ممنون :)
