### ISSUE TITLE
مشکل فونت و فرم ساعت ویجت

### ISSUE THREAD

**Issue by MrkTheCoder** [persian-calendar/DroidPersianCalendar#377]
سلام
 ساعت ویجت به فرمت ۲۴ ساعت است در حالی که در تنظیمات برنامه حالت ۲۴ ساعت را خاموش کرده ام. (البته این گزینه در تب رابط ها است و نه ویجت ها) 
 همچنین نوع فونت اعداد هم انگلیسی است و نه فارسی. زبان موبایل من انگلیسی است، اگر امکان دارد دو گزینه برای انتخاب زبان فونت اعداد ساعت و فرمت ۲۴/۱۲ ساعته را به ویجت اضافه نمایید.
با تشکر از برنامه عالیتان

**Comment by ebraminio** [comment]
سلام! دلایل فنی دارید این‌ها :/

داستان این است که ما از ویجت خود اندروید استفاده می‌کنیم که اختیار تنظیم اعداد ویجت را از ما گرفته است، البته قبلاً اینگونه نبود ولی ماجرا این است اندرویدهای جدید برای اینکه مصرف باتری را بهینه‌تر کنند برنامه‌هایی که با فرکانس زیادی خود را آپدیت می‌کنند را به کاربر گزارش مصرف باتری می‌دهند، برای حل این مشکل کارهایی نیاز به انجام بهر دقیقه‌ای داشت را از تقویم حذف کردیم و به جای اینکه عدد ساعت را خودمان تنظیم کنیم الآن ویجت ساعت آن را انجام می‌دهدد که ارقام آن هماهنگ با زبان سیستم است، قضیهٔ ۲۴ساعته بودن هم این هست که از آنجایی که ویجت سیستم آن را انجام می‌دهد نمی‌توانیم ق.ظ ب.ظ را تنظیم کنیم، اگر خودمان آن را انجام دهیم لازم است که دقیقاً سر ساعت در گوشی تایمر بگذاریم که صدا شود فقط برای اینکه ساعت ۲۴تایی ۱۲تایی شود و تازه با اعداد داخل ویجت هماهنگ نیست :/ اگر می‌شد به کامپوننت ساعت دستور داد که زبان محلی را تنظیم کند هم اصلاً مشکلی نبود و در حالت عادی ممکن هم هست ولی مشکل اینجاست که راه‌های تنظیم آن از راه دور (یعنی کامپوننت‌های صفحهٔ لاک‌اسکرین از راه دور کنترل می‌شوند) بسته است

**Comment by mrkangany** [comment]
سلام
ممنون بابت پاسخگویی و توضیحات جامع شما. پس با توجه به این توضیحات امیدوارم در آینده تنظیماتی توسط گوگل به ویجت ها اضافه شود که دو مورد فوق قابل حل باشد. موفق باشید

**Comment by ebraminio** [comment]
راه‌حلی پیدا کردم که این موضوع را البته بدون نمایش ب.ظ و ق.ظ بهبود دهد ممنونم و شرمنده بابت این زمان طی شده :)
https://github.com/persian-calendar/DroidPersianCalendar/commit/e2e029ebb6fcca3bec0c6d2c211348b9533e4f08
