### ISSUE TITLE
راست چین و چپ چین شدن تقویم

### ISSUE THREAD

**Issue by 1noisy** [persian-calendar/DroidPersianCalendar#380]
سلام. بعضی مواقع نحوه چیدمان مخیط برنامه تقویم از لحاظ چپ و راست بودن، بهم میریزه و باید برنامه را یه بار، باز و بسته کنیم

**Comment by ebraminio** [comment]
سلام اگه درست متوجه مشکل شده باشم قضیه این هست که شیوه‌ای که ما برای فارسی کردن برنامه استفاده می‌کنیم این است که اندروید رو مطلع می‌کنیم که زبان را برای یک برنامه عوض کند، این موضوع خوب است تا وقتی که خود اندروید ناگهان علاقه پیدا می‌کند که زبان گوشی را دوباره رو برنامه اعمال کند که این مشکلات پیش می‌آید ولی برای خیلی از گوشی‌ها اینگونه نیست و من هم در چند اندرویدی که داشتم این مشکل را مشاهده نکردم که برطرف کنم ولی چاره‌اش در حال حاضر این است که زبان دستگاه را فارسی کنید تا به راه حلی برسیم، ممنون :)
