### ISSUE TITLE
حذف کلمه "شمسی" از صفحه ی ویجت

### ISSUE THREAD

**Issue by ghost** [persian-calendar/DroidPersianCalendar#390]
سلام 
بر روی ویجت صفحه اگر قسمت 
کلمه ی "شمسی" حذف بشه قشنگتر میشه

دوشنبه
۱۳۹۷/۱۱/۱۱ شمسی
>

دوشنبه
۱۳۹۷/۱۱/۱۱

**Comment by ebraminio** [comment]
هممم درست می‌گویید عباس جان، فکر می‌کنم برای بعضی ویجت‌ها نیاز نباشد

**Comment by MEHDIMYADI** [comment]
سلام و عرض ادب
سعی شده برنامه یوزر فرندلی باشه و تمام کاربران دنیا ازش بتونن استفاده کنند.
اینکه انتهای هر تاریخی شمسی، میلادی یا قمری بکار برده میشه این هست که کاربر بتونه راحت تشخیص بده چرا که شاید کاربران خارجی گمراه بشوند.
بازم ممنون بابت لطفتون.

**Comment by ebraminio** [comment]
کمی گیج کننده می‌شود از طرفی دیگری ولی در طراحی ویجت‌های دیگر در نظر می‌گیریم، ممنونم :)
