### ISSUE TITLE
درست کار نکردن تراز

### ISSUE THREAD

**Issue by fakhamatia** [persian-calendar/DroidPersianCalendar#399]
وقتی از قطب نما به تراز جا به جا میشی معمولا تراز از کار میوفته
http://uupload.ir/files/o89a_photo_2019-02-17_11-37-14.jpg

**Comment by ebraminio** [comment]
یک خورده تکون نیاز دارد ولی درست می‌فرمایید باید بررسی کنم قبلآً بهتر بود
