### ISSUE TITLE
نمایش اشتباه مناسبت‌ها

### ISSUE THREAD

**Issue by codeker113** [persian-calendar/DroidPersianCalendar#403]
سلام، من وقتی از قسمت مناسبت ها، سایر مناسبت‌های ایران رو انتخاب می‌کنم باید طبیعتا مناسبت‌هایی نظیر روز درخت‌کاری ، روز پزشک و.. نشون بده ولی علاوه برا این ‌ها می‌بینم نشون میده تولد ام کلثوم ، ازدواج ابوطالب و... در صورتی که این‌ها باید تو قسمت مناسبت‌های اسلامی باشه نه سایر مناسبت‌های ایران 
آخه ام کلثوم به سایر مناسبت‌های ایران چه

**Comment by ebraminio** [comment]
درست می‌فرمایید در سایر مناسبت‌ها همه مناسبت‌هایی که در دسته‌بندی ایران قرار داده شده‌اند فعال می‌شوند

**Comment by ebraminio** [comment]
از آن موقع بهبودهای بسیاری داشته، لطفاً مجدد بررسی کنید، ممنون :)
