### ISSUE TITLE
تبدیل نمودار منحنی مقدار سپری شده روز به یک ویجت

### ISSUE THREAD

**Issue by Matjafari** [persian-calendar/DroidPersianCalendar#414]
سلام.
جعفری هستم. اپلیکیشنتونو تو کشور ژاپن استفاده میکنم. هم برای تقویم فارسی هم اوقات شرعی هم همه چی. 
ولی یه قسمت هست که از همه بیشتر عاشقشم. اون نمودار منحنیه که نشون میده چقدر از روز رفته و چقدرش مونده. تو اپ های دیگه مثل وذرِ گوگل پیداش کرده م ولی هیچکدوم به کاملی مال شما نیست که شب رو هم نشون بده و ساعت های باقیمانده و گذشته و...
میتونم ازتون خواهش کنم اون رو به صورت ویجت دربیارید که دائم جلوی چشم باشه؟؟
خواهش میکنم🙏🙏🙏

**Comment by ebraminio** [comment]
سلام! پیشنهاد خیلی جالبی بود که بهش فکر هم نکرده بودیم، ممنون

**Comment by Matjafari** [comment]
ممنونم از پاسخگویی سریعتون.
جعفری

**Comment by ebraminio** [comment]
و البته تا یادم نرفته آن قسمت نتیجه زحمت @Mehdi-Dimyadi بوده که ممنونم از ایشان :)

**Comment by Matjafari** [comment]
سپاسگزارم از ایشون، شما و همه تیمتون.

**Comment by ebraminio** [comment]
چالش‌ها و نکات پیاده‌سازی:
* نمایش پیامی مناسب هنگامی که مکان در برنامه تنظیم نباشد
* عدم امکان یا به شدت سخت بودن انیمیشن برای نمودار در یک ویجت 
* متن مناسب برای نابینایان، همان طول روز و ساعت مانده

**Comment by Matjafari** [comment]
آهان یعنی وقتی روی هوم اسکرین باشه درجا آپدیت نمیشه؟ مثلا هر بار که صفحه
میزنیم مثل انیمیشن داخل اپلیکیشن، دایره ی روش تا اون ساعت از روز نمیتونه
بیاد؟
تو نسخه های اول انیمیشن نذارید اگه خیلی مشکله.
فقط تو هر بار آنلاک کردن آپدیت بشه مثلا.
ببخشید من نمیتونم خیلی نظر تخصصی بدم چون تخصصی ندارم.
ولی اگه کمکی میکنه، آدرس پی پال بدید یه مبلغ کوچیکی برای تسریع در روند
کارتون براتون واریز کنم.
ارادتمند
جعفری

**Comment by Matjafari** [comment]
ببخشید مگه نابینایان از گوشی استفاده میکنن؟!😨

**Comment by ebraminio** [comment]
بله با امکان تاک‌بک در قسمت اکسسبیلتی در تنظیمات، این‌ها جزئیاتی بودند که گفتم جایی یادداشت کنم. نابینایان چنان استفاده حرفه‌ای از وسایل الکترونیکی می‌کنند که باعث تعجب می‌شود و بعضی جزئیات بهتر از بسیاری بینایان بلد هستند، تقویم فارسی هم تا حد خوبی برای نابینایان بهینه شده است ولی خب از جمله همین نمودار جای کار داشته که اینگونه بیشتر مشخص می‌شود و مساله‌ای نیست و جای نگرانی نیست، ممنون. :)

**Comment by Matjafari** [comment]
واقعا عالیه. خوشحال شدم از شنیدنش.
ممنون

**Comment by MEHDIMYADI** [comment]
سلام
ممنونم پیشنهاد خوبیه و داشتنش کار ساده‌ای اما باید دید تاثیر منفی در مقدار مصرف باتری نداشته باشه که باید تست بشه
خیلی ممنونم بازم پیشنهاد و درخواست ویژگی‌های جدید بود حتما به ما اطلاع بدید.

**Comment by Matjafari** [comment]
سلام
ممنونم از شما و پاسخگوییتون.
اپلیکیشن تقویم فارسی تون همیشه اولین اپلیکیشنیه که روی گوشی های جدید نصب
میکنیم.
همین الانشم بی نقص و عالیه.
اما علاوه بر چیزی که گفتم، پیشنهاد های دیگه ای هم دارم که البته توقع خیلی
زیادیه برای اپلیکیشنی که رایگانه و همچنین من در زمینه برنامه نویسی سررشته
ای ندارم و نمیدونم این پیشنهادها تا چه حد ساده یا سخته اما اگر دوست داشتید
روشون فکر کنید:
 ۱-من یک اپلیکیشن به نام sleep as android رو  همیشه توی گوشیم دارم. (عکس
های مربوط به اپ رو ضمیمه کرده م)
تو این اپلیکیشن تنظیم کرده م که مثلا یک ربع قبل از طلوع آفتاب بیدار بشم
(قابلیتی که اپلیکیشن شما هم داره)
با این که فضا و رم زیادی اشغال میکنه و گوشیم رو به شدت کند میکنه، مجبورم که
نگهش دارم. چون یکی از معدود اپلیکیشن های آلارم داره که آپشن gentle volume
increase رو داره.
من گوشیم رو قبل خواب کنار بالشم میذارم و اگه این آپشن نباشه و صدای آلارم یا
اذان یکدفعه شروع به پخش بکنه، خیلی ترسناک هست. (میدونم میشه صداش رو کم کرد
ولی هر صدای کمی تو سکوت اول صبح خیلی بلند به نظر میرسه)
همینطور وقتی ک مثلا تو محل کار نشسته م و یکدفعه از گوشیم صدای اذان بلند
میشه یکم برای بقیه سوال بر انگیزه ولی اگه با صدای کم شروع کنه میتونم سریعا
خاموشش کنم (راستی اینجا بگم که بابت اون قابلیت خاموش کردن با دوبار زدن رو
صفحه واقعا متشکرم. خیلی راحته)
اگه این آپشن رو اضافه کنید، یه اپ رو میتونم بطور کامل از گوشیم حذف کنم و
ممنون شما بشم.
۲- من برای برنامه ریزی روزانه از گوگل کالندر استفاده میکنم، بعضی از کارهایی
که میخوام در یک روز خاصی از تقویم ایران انجام بدم یا یک روزهایی که برام
مهمه رو باید از اپلیکیشن شما پیدا کنم و میرم تو اپ کالندر و اون روز رو ثبت
میکنم.
خیلی عالی میشد اگه اپلیکیشن شما مثل اپلیکیشن any do به گوگل کالندر لینک
میشد و مناسبت ها رو تو کالندر نشون میداد.
این چیزهایی بود که به نظرم میرسید.
بازهم ممنونم
جعفری

**Comment by ebraminio** [comment]
سلام، ۱ رو با تغییر صدای اذان هم می‌تونید انجام بدید که در حال جاضر وجود داره در برنامه و می‌شه صداهای متنوع گذاشت ولی خب این gentle volume رو نداره و می‌تونیم بهش فکر کنیم
دربارهٔ ۲، همین الآن هم برنامه می‌تونه رویدادهای تقویم گوگل رو هم نشون بده کافیه رویدادهای شخصی رو فعال کنید

**Comment by Matjafari** [comment]
نکته دقیقا همون gentle volume increase هست.
با زدن رویداد های شخصی، از کالندر میاد تو برنامه نه برعکس، درسته؟ ولی به هر
حال همین رو هم نمیدونستم ممنون.

**Comment by ebraminio** [comment]
اگر روی یک روز نگه دارید رویدادی که اضافه می‌کنید به تقویم اصلی هم اضافه می‌شود که برنامه آن را هم نشان می‌دهد

**Comment by ebraminio** [comment]
برای ارجاع سایر توسعه‌دهندگان، البته کار نمی‌کند ولی احتمالاً بشود راه انداختش

https://github.com/ebraminio/DroidPersianCalendar/tree/sunviewwidget

**Comment by ebraminio** [comment]
انجام شد، در نسخهٔ بعد قابل مشاهده خواهد بود :)

**Comment by ebraminio** [comment]
> نکته دقیقا همون gentle volume increase هست.

اذان افزایشی مدت بیشتری است که اضافه شده، امیدوارم همون چیزی باشه که نیاز داشتید اگر نه هم حتماً بفرمایید :)
