### ISSUE TITLE
درخواست امکانات جدید

### ISSUE THREAD

**Issue by sadrav** [persian-calendar/DroidPersianCalendar#425]
ورود تاریخ شمسی
محاسبه سن: سال - ماه - روز   برابر با .... روز

اختلاف بین دو تاریخ
ورود تاریخ اول       ورود تاریخ دوم
تفاوت: ....سال ....ماه ..... روز معادل .....روز

بسیار کاربردی برای واحدهای کارگزینی و حسابداری که احتمال استفاده از این قسمت تقویم را روزانه افزایش خواهد داد

**Comment by ebraminio** [comment]
سلام! اولیکه وجود دارد دیگر؟ هم در مبدل هم در صفحهٔ اصلی اگر از گزینه برو به استفاده کنید و به روز مورد نظر بروید اختلاف تا امروز را خواهید داشت. اختلاف بین دو تاریخ هم اگر دو تاریخ را تبدیل کنید، اگر هر دو بعد یا قبل از امروز باشند با کم کردن از همدیگر می‌شود اختلاف و اگر یکی بعد یکی قبل باشد می‌شود با جمعشان ممکن است :) البته قبول داریم راه حل بهتری می‌تواند داشته باشد، انتخاب دوروز کمی دردسر می‌شود فکر می‌کنم

**Comment by ebraminio** [comment]
ادغام با #362
