### ISSUE TITLE
تقویم فارسی

### ISSUE THREAD

**Issue by mohamadni** [persian-calendar/DroidPersianCalendar#437]
سلام ، لطفا تنظیمات شخصی سازی واسه پوسته اعلان بزارید ، من همیشه از حالت دارک مود اندروید استفاده میکنم چون کلا نور سفید اذیتم میکنه ، ولی اعلان شما سفید میمونه و وقتی نوار ابزار رو میکشم پایین چشم رو اذیت میکنه ، لطفا یه گزینه واسه تغیر رنگ پس زمینه اعلان قرار بدید که کسایی مثل من دچار مشکل نشن
ممنون از برنامه خوبتون

**Comment by ebraminio** [comment]
برای من به درستی تاریک می‌شود
![image](https://user-images.githubusercontent.com/833473/57282227-de2cfc80-70c1-11e9-8606-4428fd276ed8.png)
نمی‌دانم سامسونگ چه کرده‌اند که بعضی برنامه‌ها را تاریک می‌کند بعضی‌ها را نه ما گزینه‌ای برای آن نداریم، ببینیم نظر سایر دوستان چیست

**Comment by alirezaivaz** [comment]
مال من که هوآویه و چیزی به اسم دارک مود نداره، کلا دارکه :) قاعده و قانون خاصی از قرار نداره.

**Comment by alirezaivaz** [comment]
ولی اینکه بشه رنگ‌بندی رو تغییر داد، خیلی جذابه

**Comment by ebraminio** [comment]
اعلان تاریک سامسونگ تو نسخه بعد که کم‌کم در حال انتشاره درست می‌شه :)
