### ISSUE TITLE
تایم اذان اشتباه است

### ISSUE THREAD

**Issue by SLjavad** [persian-calendar/DroidPersianCalendar#438]
سلام
زمانی که برنامه برای اذان نوشته با زمان واقعی حدود 9 دقیقه تفاوت دارد

**Comment by ebraminio** [comment]
سلام گرامی ما از الگوریتم 
http://praytimes.org/
استفاده می‌کنیم ولی کاربران مختلف گفته‌اند اختلاف چنددقیقه‌ای دارد، ایده‌ای ندارم چه کنیم :/

**Comment by alirezaivaz** [comment]
یه فایل توی فولدر raw هست به اسم cities.json توی اون باید موقعیت جغرافیایی شهرها رو عوض کرد. مثلا مشهد توی طول و عرض با واقعیت ۱ درجه فاصله داره و بیشتره که باید عوض بشه. اگه بتونم فایل تغییریافته رو براتون میفرستم تا اعمالش کنید (البته اگه بخواید)

**Comment by ebraminio** [comment]
عاااالی

**Comment by ebraminio** [comment]
با تنظیم مجدد شهر در نسخهٔ جدید بسیار دقیق‌تر می‌شود، تا بررسی نسخهٔ بعد این فایل را می‌بندم

**Comment by ebraminio** [comment]
و با تشکر از علیرضا :)
