### ISSUE TITLE
تقویم ۹۸

### ISSUE THREAD

**Issue by Abolfazl-ec** [persian-calendar/DroidPersianCalendar#439]
دوشنبه تعطیله ۶ خرداد ن یکشنبه

**Comment by runo280** [comment]
امسال ماه شعبان سی روزه شد
و از اونجایی که این قبیل رخداد ها قابل پیش بینی نیست
توی تنظیمات تقویم با گزینه «تنظیم تقویم اسلامی» میتونید تاریخ قمری رو اصلاح کنید:
گزینه «منفی یک» رو باید انتخاب کنید

**Comment by ebraminio** [comment]
با عرض شرمندگی، بابت صبرتون ممنونم

**Comment by ebraminio** [comment]
خصوصاً سعی می‌کنم سال بعد نگذارم چنین شود
