### ISSUE TITLE
تغییر در شیفت های کاری

### ISSUE THREAD

**Issue by medicamin** [persian-calendar/DroidPersianCalendar#453]
سلام،

اگر بشود در تنظیم شیفت های کاری، بتوانیم بجای مقادیر پیشفرض استراحت،روزکاری،عصرکاری،شب کاری، موارد دلخواه را وارد کنیم، و همچنین در یک روز بشود بیش از یک شیفت تعیین کرد، امکان خوبی خواهد بود.
مثلا ممکن است یک نفر بجای عصر و شب و روز، بخواهد بنویسد اورژانس، تریاژ، اسکرین، بخش داخلی و ...

با تشکر

**Comment by ebraminio** [comment]
سلام امین، یکم اذیت هست خصوصاً از نظر ظاهر ولی حق دارید درست هست توقع‌تون، ممنونم

**Comment by medicamin** [comment]
میتونید در منویی که آیتم ها رو نوشته یه گزینه بذارید: دلخواه
و بعد وقتی کاربر اون رو انتخاب میکنه یه فیلد زیرش باز شه و بتونه بنویسه.

و در محیط خود تقویم هم عبارت هایی مثل روزکاری خیلی بزرگ و زشت نشون داده میشن. این هم اگر اصلاح کنید خیلی خوب میشه.

**Comment by ebraminio** [comment]
در نسخه جدید درست شده است بررسی فرمایید ممنون :) 
https://github.com/persian-calendar/DroidPersianCalendar/releases/download/v6.1.4/PersianCalendar-release-6.1.4-master-2689-72dd0adf.apk
