### ISSUE TITLE
 صدای اذان افزایشی باشد

### ISSUE THREAD

**Issue by ebraminio** [persian-calendar/DroidPersianCalendar#455]
از ایمیل‌های دریافتی

**Comment by alirezaivaz** [comment]
به‌نظر من این یک ویژگی خوب است. البته باید به‌صورت چک‌باکس در تنظیمات باشد تا اگر کسی نخواست، فعالش نکند. هم‌چنین این ویژگی برای صدای برخی موذن‌ها (مانند مرحوم مؤذن‌زاده) واقعا جذاب هست.

**Comment by ebraminio** [comment]
بله درست است

**Comment by runo280** [comment]
I'm working on it
