### ISSUE TITLE
تغییر رنگ نوار اعلانات

### ISSUE THREAD

**Issue by mrdanesh37** [persian-calendar/DroidPersianCalendar#475]
سلام. لطفا ترتیبی برای نرم افزار تقویم دوست داشتنی تون اتخاذ کنید ک در نوار اعلانات هم همزمان رنگ عوض کند، یا همزمان با حالت شب هم رنگ بقیه اعلانات گوشی شود. باتشکر.

**Comment by ebraminio** [comment]
سلام گرامی در نسخهٔ جدید بالید درست شده باشد، 
https://github.com/persian-calendar/DroidPersianCalendar/releases/download/v6.1.4/PersianCalendar-release-6.1.4-master-2689-72dd0adf.apk
بررسی می‌فرمایید؟ ممنونم

**Comment by ebraminio** [comment]
با فرض این مشکل برطرف شده است این فایل را می‌بندم ولی لطفاً مطلعمان کنید ممنونم

**Comment by mrdanesh37** [comment]
هنوز مشکل برطرف نشده، بعد از هربار نصب مجدد تا لحظاتی درست است ولی بعد از
مدتی دوباره حالت شب غیر فعال میشود.
