### ISSUE TITLE
وسط‌چین شدن ویجت‌ها

### ISSUE THREAD

**Issue by Arman1512** [persian-calendar/DroidPersianCalendar#484]
سلام. توی تنظیمات تقویم گزینه‌ای برای وسط‌چین شدن ویجت‌ها وجود داره که نوشته‌های داخل ویجت رو فقط از نظر چپ و راست بودن وسط‌چین میکنه. میشه یه گزینه‌ای اضافه کنید که نوشته‌های ویجت رو از نظر بالا و پایین بودن هم وسط چین کنه به طوری که نوشته‌های ویجت به کادر بالایی ویجت نچسبیده باشن؟

**Comment by ebraminio** [comment]
اوه شرمنده ندیده بودم گرامی، کدام ویجت بیشتر مورد نظر است؟ در نسخهٔ اخیر که در بتای گوگلی پلی وجود دارد بعضی از ویجت‌ها را از نظر عمودی نیز وسط چین کردم لطفاً بررسی کنید، ممنونم

**Comment by ebraminio** [comment]
برای بعضی اصلاح شده باز هم مشکلی بودید ما را مطلع کنید ممنون :)
