### ISSUE TITLE
کرش مکرر برنامه بعد از آپدیت به 6.1.2

### ISSUE THREAD

**Issue by mhosem** [persian-calendar/DroidPersianCalendar#487]
Sony Xperia Z5
Android 7.1.1

**Comment by ebraminio** [comment]
سلام گرامی لطفاً نسخهٔ ۶.۱.۳ را بیازمایید و حتماً نتیجه را به ما نیز بگویید ممنونم
https://github.com/persian-calendar/DroidPersianCalendar/releases/tag/v6.1.3

**Comment by mhosem** [comment]
با آپدیت جدید مشکل حل شد، ممنون

**Comment by ebraminio** [comment]
اوه ممنونم

در تاریخ شنبه ۱۹ اکتبر ۲۰۱۹،‏ ۲۲:۰۸ mhosem <notifications@github.com> نوشت:
