### ISSUE TITLE
ایجاد ویجت خورشیدنما

### ISSUE THREAD

**Issue by ebraminio** [persian-calendar/DroidPersianCalendar#497]
به طور ساده خورشیدنما (ظاهر خورشیدی در تب سوم صفحهٔ اصلی تقویم اگر مکان در تنظیمات تنظیم باشد) در یک ویجت قرار داده شود، من اینجا تلاشی کردم

https://github.com/persian-calendar/DroidPersianCalendar/tree/sunviewwidget2

ولی نشد ویجت را بکشم به خاطر همین گفتم اینجا بنویسم

**Comment by behrouz66** [comment]
ایده بیار خوبیه اتفاقن

https://batask.ir

**Comment by ebraminio** [comment]
انجام شد
