### ISSUE TITLE
Remove extra trailing comma in long date format

### ISSUE THREAD

**Issue by hmehr** [persian-calendar/DroidPersianCalendar#506]
![Screenshot_20191027-074318](https://user-images.githubusercontent.com/2472035/67634028-8495d580-f88d-11e9-9cc6-4cb933a13e16.png)

When using the widget, there's an extra trailing comma in the long shamsi date format. This can be easily removed to enhance user experience.

**Comment by ebraminio** [comment]
سلام گرامی اگر در شخصی‌سازی ویجت‌ها نمایش سایر تقویم‌ها را بردارید دیگر کاما نمی‌گذارد، لطفاً آزمایش کنید :) ممنون
