### ISSUE TITLE
اعلام اشکال در برنامه تقویم فارسی

### ISSUE THREAD

**Issue by martyr72** [persian-calendar/DroidPersianCalendar#518]
به نام خدا
سلام. در نسخه جدید برنامه بسیار عالی تقویم فارسی، سه اشکال متصور است:
۱ قبلاً در زمانیکه صفحه نمایش خاموش بود هنگام پخش اذان صفحه نمایش روشن می‌شد و تصویر مربوطه را نمایش می‌داد ولی اکنون صفحه نمایش خاموش می‌ماند و فقط صدای اذان پخش میشه
۲ در قطع صدای اذان چون صفحه نمایش خاموش است باید ابتدا کلید پاور را فشار داد تا پس از نمایش تصویر اذان و لمس صفحه نمایش, صدا را بتوان قطع کرد
۳ بعد از قطع صدای اذان به شکل بالا، پس از تقریبا ۲ یا ۳ ثانیه دیگر مجدداً اذان از ابتدا پخش می‌شود

با سپاس و آرزوی موفقیت

**Comment by ebraminio** [comment]
باید در نسخهٔ اخیر بهتر شده باشد، لطفاً بررسی فرمایید، ممنونم :)
