### ISSUE TITLE
اسامی روزهای هفته به فینگلیش برای زبان انگلیسی (ایران)

### ISSUE THREAD

**Issue by xmha97** [persian-calendar/DroidPersianCalendar#519]
سلام
من زبان برنامه رو
English (Iran)
قرار دادم.
لطفا روزهای هفته رو از
`ش`	`ی`	`د`	`س`	`چ`	`پ`	`ج`
به
`Sh`	`Ye`	`Do`	`Se`	`Ch`	`Pa`	`Jo`
تغییر بدید.
با تشکر.

![JCal](https://user-images.githubusercontent.com/23485114/68829009-bb0c8680-06bc-11ea-8ea7-7bc9756e83ee.png)

**Comment by ebraminio** [comment]
فکر جالبی بود، ببخشید دوسال دیر، از اون موقع تمیزکاری‌های خیلی زیادی داشتیم که الآن انجامشو خیلی راحت کرده، اعمال شد، ممنونم :)

<img width="357" alt="image" src="https://user-images.githubusercontent.com/833473/133336094-c42812c3-89c2-4bd2-9148-d8268ab868b2.png">

**Comment by xmha97** [comment]
مرسی از شما، واقعا لطف کردید. 🙏
