### ISSUE TITLE
اشتباه محاسباتی

### ISSUE THREAD

**Issue by VAHIDBAYAT** [persian-calendar/DroidPersianCalendar#521]
باسلام عرض خسته نباشید
برنامه در گوشی آ هفتاد در مدل ساعت۲۴ ساعته در محاسبه زمان باقی مانده تا اذان صبح دچار اشکال است

**Comment by ebraminio** [comment]
سلام گرامی درست می‌فرمایید در نسخهٔ بعد اصلاح می‌شود ممنونم :)
