### ISSUE TITLE
مشکل در اپدیت آخر

### ISSUE THREAD

**Issue by irmacfa** [persian-calendar/DroidPersianCalendar#525]
سلام من آپدیت کردم یه مشکل عجیبی دارم هر وقت از کزینه بستن تمامی برنامه ها استفاده میکنم ، تقویم هم بسته میشه ، قبلا با بسته شدن این فرایند چنین مشکلی پیش نمیامد

**Comment by ebraminio** [comment]
فکر می‌کنم این مشکل از زمان انتقال از سرویس‌ها به ورک‌منیجر روی داده است که چاره‌ای هم نداشته باشد :/ ظاهراً یک علامت قفلی در کنار برنامه‌ها در این گوشی‌ها در منوی برنامه‌های اخیر قرار دارد که با زدن آن مشکل تا حدی بهبود میابد، شرمنده کار بیشتری ازمان بر نمی‌آید تاجایی که می‌دانم :/ ممنون :)
