### ISSUE TITLE
باز نشدن برنامه پس از کلیک بر روی ویجت عدد روز در نوتفیکشین دراور

### ISSUE THREAD

**Issue by xeoncode** [persian-calendar/DroidPersianCalendar#528]
با سلام. در نسخه جدید وقتی روی آیکون عدد نمایش دهنده تاریخ روز جاری که در نوتفیکیشن دراور در کنار دکمه تنظیمات، وای فای ،بلوتوث و... قرار دارد کلیک میکنم متاسفانه برنامه باز نمیشه. در نسخه ای از
 برنامه که مهر ماه نصب کرده بودم این مشکل وجود نداشت  اما الان وقتی رو دکمه کلیک میکنیم هیچ اتفاقی نمی افته.
![Screenshot_2019-12-18-00-24-08-439_com android chrome](https://user-images.githubusercontent.com/3122952/71033598-ddb31480-212c-11ea-8f70-b26f14912462.png)

**Comment by ebraminio** [comment]
سلام گرامی چنین چیزی را دیده‌ام ولی از آنجایی که الآن برایم درست کار می‌کند واقعیتش کاری نمی‌توانم کنم ببینم کجاها چنین مشکلی ندارد

**Comment by ebraminio** [comment]
امیدوارم تا الآن برطرف شده باشد اگر نه واقعاً جای محدودیتی است که اگر کار نکند کار خاصی نمی‌توانیم در رابطه با آن انجام دهیم، ممنون :)
