### ISSUE TITLE
تغییر رنگ تاریخ در نوار اعلان

### ISSUE THREAD

**Issue by YasserDivaR** [persian-calendar/DroidPersianCalendar#534]
سلام دوستان
با سپاس از برنامه محبوب
و خسته نباشید خدمت تک تک عزیزان توسعه دهنده
آیا امکان تغییر رنگ شماره روز در قسمت اعلان ها کنار ساعت گوشی امکان پذیر هست؟

**Comment by ebraminio** [comment]
سلام یاسر جان کجا را می‌فرمایید؟ یک عکس تهیه می‌فرمایید؟ ممنونم

**Comment by YasserDivaR** [comment]
@ebraminio 
بالا کنار ساعت و دقت بفرمایید
مثلا برای منی که تصویر زمینه روشن انتخاب کردم
رنگ عدد تاریخ مشکی هست ولی اگر بشه رنگ پس زمینه اونو از حالت 
Transparent به مشکی تغییر داد بهتر بود. حاشیه گرد اطراف اون باشه
https://file.soft98.ir/uploads/yasserdivar/2020/03/02_03-photo-2020-03-02-23-13-16.jpg
که بهتر توی چشم بیاد ، تقویم های دیگه رو تست کردم راحت میشد تغییر داد ولی داخل تنظیمات هم رفتم منتها تاثیری نداشت

**Comment by ebraminio** [comment]
تاجایی که می‌دانم گرامی رنگ این قسمت، به مانند سایر آیکون‌هایی که در تصویر دارید، قابل تغییر نستند یا اگر باشد دردسری می‌شود :/ شرمنده
