### ISSUE TITLE
Can't solve databinding error

### ISSUE THREAD

**Issue by andysagar** [persian-calendar/DroidPersianCalendar#535]
Unable to find solution of missing this path error

import com.byagowi.persiancalendar.databinding

**Comment by ebraminio** [comment]
It is generated by the build system. Is your setup ok? We have whole app built in CI also and pretty sure you are able to build the app using `./gradlew build`.

**Comment by andysagar** [comment]
i am facing this error in android studio 

view Binding.isEnabled = true ^ Unresolved reference: view Binding

**Comment by ebraminio** [comment]
You should use Android Studio 3.6.0 RC versions to have access to viewbinding.

**Comment by andysagar** [comment]
Ok thank you
