### ISSUE TITLE
تغییر فونت فارسی

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [persian-calendar/DroidPersianCalendar#536]
لطفا از فونت‌های آزادِ **وزیر**، **شبنم** یا **استعداد** بجای فونت فعلی در تقویم فارسی استفاده کنید

**Comment by ebraminio** [comment]
ادغام با #527، ممنونم از شما، فونت استعداد هم فوق‌العاده است متأسفانه حروف زبان پشتو را ندارد

![image](https://user-images.githubusercontent.com/833473/75634221-fa85c100-5c20-11ea-8c2c-172cd0a09fa2.png)
