### ISSUE TITLE
سلام لطفا کمک کنید 

### ISSUE THREAD

**Issue by Ahoora9433** [persian-calendar/DroidPersianCalendar#545]
من تمام یاد اور هام یک روز رفته جلو توی اپدیت امسال باید چکار بکنم

**Comment by ebraminio** [comment]
سلام گرامی یادآورهای سالانه را می‌فرمایید؟ چرخش یادآورهای تقویم گوشی به صورت میلادی است نه شمسی و کار زیادی از دست ما برنمی‌آید

**Comment by Ahoora9433** [comment]
هیچ راهی براش نداریم؟ کاریش نمیتونم بکنم؟ بشینم از اول نتظیم بکنم؟ و اینکه
از این بعد سالانه ذخیره نکنیم؟

در تاریخ پنجشنبه ۹ آوریل ۲۰۲۰،‏ ۱۹:۴۰ Ebrahim Byagowi <
notifications@github.com> نوشت:

**Comment by ebraminio** [comment]
درست است و ما کنترلی نداریم، یعنی اطلاعات رویدادها توسط تقویم فارسی نگه‌داری نمی‌شوند و توسط تقویم دستگاه نگه‌داری می‌شود که دارای امکان گردش سالانهٔ شمسی نیست، اگر تقویم فارسی قرار به نگه‌داری آن‌ها داشت آن وقت نمی‌شد به راحتی با تقویم دستگاه آن را سینک کرد و دردسرهایی برای یادآوری هم می‌داشت، وضعیت ایده‌الی نیست ولی چاره‌ای هم نداریم

**Comment by Ahoora9433** [comment]
بله خیلی خیلی ممنونم بابت جواب صادقانه و منطقی شما.    روز بخیر......

در تاریخ پنجشنبه ۹ آوریل ۲۰۲۰،‏ ۱۹:۴۵ Ebrahim Byagowi <
notifications@github.com> نوشت:

**Comment by ebraminio** [comment]
همچنین گرامی :) و شرمنده که راه‌حل بهتری نداریم که الآن رویدادهایتان جای مناسبی نیست، پشتیبانی تقویم فارسی و سایر تقویم‌ها در خود گوگل کلندر باید توسط گوگل بهبود یابد که معطل می‌کنند

**Comment by Ahoora9433** [comment]
یه پیشنهاد....... ما میتونیم توی سورس برنامه به طریقی تنظیم کنیم ک در
سالهای کبیسه رویداد های میلادی رو یک روز زود تر نمایش بده و یه الارم داخلی
هم براش بزاریم

در تاریخ پنجشنبه ۹ آوریل ۲۰۲۰،‏ ۱۹:۴۹ Ebrahim Byagowi <
notifications@github.com> نوشت:

**Comment by ebraminio** [comment]
مشکل هشدار خود تقویم که در روز اشتباه انجام خواهد داد باقی می‌ماند که آنجا اصلاً با تقویم فارسی هماهنگ نمی‌شود، یا اگر مناسبت خود در سال کبیسه تنظیم شده باشد احتمالاً دردسر خواهد داشت و این مشکل به شکل جدی‌تری برای تقویم قمری هم وجود دارد که در برنامه امکان تنظیم شدن به عنوان تقویم اصلی هست، در کل تنظیم سالانهٔ فقط به صورت میلادی در حال حاضر مقدور است

**Comment by Ahoora9433** [comment]
باز هم سپاسگزارم.. موفق باشید. خوشحالم ک چنین تیمی توی کشور داریم روزتون
خوش

در تاریخ پنجشنبه ۹ آوریل ۲۰۲۰،‏ ۲۰:۰۰ Ebrahim Byagowi <
notifications@github.com> نوشت:
