### ISSUE TITLE
تنظیم جداگانه تقویم‌های قابل نمایش

### ISSUE THREAD

**Issue by 1997alireza** [persian-calendar/DroidPersianCalendar#547]
سلام. خوبه که بشه تقویم‌هایی که میخوایم داخل اپ نمایش داده بشن، با اونایی که توی اعلان نشون داده میشن تنظیم جداگانه‌ای داشته باشن. مثلا داخل اپ میلادی رو نشون بده اما توی اعلان فقط شمسی باشه.

**Comment by ebraminio** [comment]
یکم سخت و بعید هست که انجام بشه، شرمنده، ممنونم :)
