### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by faramarzaf** [persian-calendar/DroidPersianCalendar#549]
لطفا این تقویم رو در قالب یک کتابخونه قرار بدید

**Comment by ebraminio** [comment]
مجوزی که از اول باهاش پیش رفتیم خیلی مناسب اینکار نیست به خاطر همین بعیده، ولی قسمت‌ها مختلفی که راحتتر تونستیم جدا کنیمو در مخزن‌های جدا قرار دادیم، ممنونم
