### ISSUE TITLE
لایسنس

### ISSUE THREAD

**Issue by mojtaba7b** [persian-calendar/DroidPersianCalendar#550]
سلام خسته نباشید
لطفا توضیح بیشتری راجب لایسنس برنامه بفرمائید
مثلا الان همه برنامه ها تو مارکت ها را در لیست اخطار و حذف قرار دادید
ایا امکان تغیر ایکون و نام برنامه هست؟
مثلا الان من برنامه را همان گونه که سورس هست قرار دادم و در توضیحاتم لینک کردم و فقط ایکون و نام برنامه 
را تغیر دادم ولی بازم مارکت بازار قبول نمیکنه و میگه طبق لایسنس باید اپدیت بدید
لطفا راهنمایی بفرمائید
ممنون

**Comment by ebraminio** [comment]
سلام در اینجا افزوده شده

https://github.com/persian-calendar/DroidPersianCalendar#%D9%85%D8%AC%D9%88%D8%B2-%D8%B4%D8%B1%D8%A7%DB%8C%D8%B7-%D8%A7%D8%B3%D8%AA%D9%81%D8%A7%D8%AF%D9%87-%D8%A7%D8%B2-%DA%A9%D8%AF-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87

در اینجا هم خلاصه‌تر توضیح داده شده

https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

قسمت must

خلاصهٔ خلاصه‌اش این است که به همراه هر انتشار باید سورس تغییراتتون رو عمومی قرار دهید چون از کدهایی در این برنامه استفاده شده که این الزام را می‌آورند و در اختیار ما نیست که شرایط دیگری برای آن‌ها قرار دهیم

**Comment by mojtaba7b** [comment]
پس ایا امکان داره سورسا و تغیراتی که دادیم در گیت هاب قرار دهیم ودر توضیحات لینک کنیم به سورس اصلی شما؟

**Comment by ebraminio** [comment]
به سورس برنامه‌تون پیوند بدید و در هر انتشار هم اون رو آپدیت کنید، هدف این مجوز این بوده که کدهای باز و عمومی در ادامه هم باز بمونن، مثل هستهٔ لینوکس که تغییراتش رو منتشر می‌کنن، یه چیز رایج هست تو نرم‌افزار

**Comment by mojtaba7b** [comment]
ممنون از راهنمایی
