### ISSUE TITLE
كيف تغير سنة فارسية 1399 إلى سنة كردية 2720

### ISSUE THREAD

**Issue by Hiwaselah** [persian-calendar/DroidPersianCalendar#555]
كيف تغير سنة فارسية 1399 إلى سنة كردية 2720
رحمك لوالديك للجواب

چۆن بتوانم ساڵی فارسی لە بەرنامەکەدا بگۆڕم لە ١٣٩٩ بۆ ساڵی کوردی ٢٧٢٠

How can I change the Persian year in the program from 1399 to Kurdish 2720 year

**Comment by ebraminio** [comment]
Hi. Nice multilingual bug report :) is that considered official calendar by any government? Something defintely worth to think about. Thanks!

**Comment by Hiwaselah** [comment]
اخي اني كورد لازم للكودستان تغير تقويم شمسي إلى كردي
أخي ، أنا كردي ، أولا جزاك الله خيرا على هذا البرنامج المفيد ، ولكن كما تعلمون ، فإن السنة الكردية تختلف عن السنة الإيرانية.
لكي يتخلص شعب كردستان مني ، كنت بحاجة إلى تغيير السنة الإيرانية من ١٣٩٩ إلى ٢٧٢٠ ... أتمنى لك يومًا لطيفًا.

براکەم من کوردم دەست خۆشیتان لێ دەکەم بۆ ئەو بەرنامە بێ وێنە و بە سوودە بەڵام وەکو دەزانن ساڵی کوردی جیاوازە لە ساڵی ئێرانی جا بۆ ئەوەی خەڵکی کوردستان سوردی لێ وەربگرن پێویستم بەوە بوو ساڵە ئێرانییەکە لە ١٣٩٩ بگۆڕم بۆ ٢٧٢٠... دەستتان خۆش بێت...

My brother, I am a Kurd, I would like to congratulate you on this unparalleled and useful program, but as you know, the Kurdish year is different from the Iranian one.
In order for the people of Kurdistan to get rid of me, I needed to change the Iranian year from 1399 to 2720 ... Have a nice day ...

**Comment by Hiwaselah** [comment]
![20200508_142510](https://user-images.githubusercontent.com/20328840/81401538-3153e800-9138-11ea-826a-f47fcf4fd158.jpg)

**Comment by Hiwaselah** [comment]
خداوند پدر و مادر شما را رحمت کند برادر من فقط نام پرونده ای را برای من ارسال می کند که سال فارسی را تغییر می دهد.
My brother just send me the name of the file that will change the Persian year.
أخي فقط أرسل لي اسم الملف الذي سيغير السنة الفارسية.
براکەم تەنها ناوی ئەو فایلەم بۆ بنێرە کە ساڵی فارسی تێدا دەگۆڕی.

**Comment by Hiwaselah** [comment]
@ebraminio خداوند پدر و مادر شما را رحمت کند برادر من فقط نام پرونده ای را برای من ارسال می کند که سال فارسی را تغییر می دهد.
My brother just send me the name of the file that will change the Persian year.
أخي فقط أرسل لي اسم الملف الذي سيغير السنة الفارسية.
براکەم تەنها ناوی ئەو فایلەم بۆ بنێرە کە ساڵی فارسی تێدا دەگۆڕی.

**Comment by ebraminio** [comment]
>  My brother just send me the name of the file that will change the Persian year.

Hmm, this is actually a good idea, an option to change year upon user request

**Comment by Hiwaselah** [comment]
ئەوە لینکی وەشانی پێشووە بۆ کوردستان:
هذا هو الرابط إلى النسخة السابقة لكردستان:
این پیوند نسخه قبلی برای کردستان است:

https://play.google.com/store/apps/details?id=com.hiwaselah.kurdishcalendar

تکایە یارمەتیم بدە تەنها ناوی ئەو فایلەم بۆ بنێرە کە ساڵی فارسی تێدا دەگۆڕی بۆ کوردی
Please help me just send me the name of the file that will change the Persian year to Kurdish.
لطفا به من کمک کنید فقط نام پرونده ای را منتشر کنید که سال فارسی را به کردی تغییر می دهد.

**Comment by ebraminio** [comment]
Hmmm, interesting, so why not using that app? I don't how they have made it, it doesn't belong to us and not supported by us also.

I was going to implement something similar but apparently you are not interested on it anymore?

**Comment by ebraminio** [comment]
Check you email. Thanks!

**Comment by Hiwaselah** [comment]
جزاك الله خيرا برای بەڕێزم خوای گەورە لێت ڕازی بێت و سەرکەوتووت بکات لە دونیا و قیامەت
باشد که خداوند شما را ، برادر عزیزم برکت دهد و او شما را در این دنیا و آخرت برکت دهد.
May God bless you, my dear brother, and may He bless you in this world and in the Hereafter.
