### ISSUE TITLE
ناقص بودن مناسبت ها

### ISSUE THREAD

**Issue by jamesongrey** [persian-calendar/DroidPersianCalendar#558]
نبود مناسبت هایی مثل روز جهانی مادر یا مناسبت های داخلی مثل روز دندانپزشک در لیست مناسبت های بین المللی و داخلی
مناسبت های دیگر را بررسی نکردم

**Comment by ebraminio** [comment]
سلام گرامی، هر دو موجود هستند کافی است از تنظیمات، مناسبت‌های مورد نظر را فعال کنید، اگه حوصله داشتید این فایل مناسبت‌هاست

https://github.com/persian-calendar/DroidPersianCalendar/blob/master/PersianCalendar/src/main/res/raw/events.json

اگر مایل بودید مناسبت‌هایی که موجود نیستند را می‌شود افزود، ممنونم :)

**Comment by jamesongrey** [comment]
بله در فایل روز دندانپزشک ۲۳ فروردین درج شده ولی بنده همه رو فعال کردم ولی هیچ مناسبتی رو برای ۲۳ فروردین نشون نمیده
خودتون هم لطفا چک کنید

**Comment by ebraminio** [comment]
درست می‌فرمایید گرامی آن را در 

https://github.com/persian-calendar/DroidPersianCalendar/commit/1dd711b3656faaffa78aca9dd6c3a55a5f43e6d3#diff-b433bbf41aae53a14589bbc3ae4bd691

افزوده‌ام که هنوز به انتشار نرسیده است، این مدت درخواست‌های جداگانه افزودن مناسبت‌های خوبی داشته‌ایم اگر خواستید حتماً خودتان هم نگاه کنید چه چیزی کم است که بیافزاییم که در نسخهٔ بعد قرار داده شود :)

**Comment by reg3xp** [comment]
هنوز در نگارش 6.4.1 برطرف نشده

**Comment by ebraminio** [comment]
درست است از آن موقع رویدادهایمان را با
https://calendar.ut.ac.ir/Fa/News/Data/Doc/Calendar%201400-Full.pdf
منطبق کرده‌ایم که مسئولیت قضاوت درباره بودن یا نبودن یک رویداد و عنوان آن‌ها را به خود مرکز تقویم دانشگاه تهران سپرده‌ایم، اگر رویدادی آنجا وجود ندارد لطفاً با ایمیلی که در سایتشان در
https://calendar.ut.ac.ir  
برای افزودن رویدادی جدید تماس بگیرید، ممنونم

**Comment by reg3xp** [comment]
در این صورت راه حل بهتر این است که رویدادهای دیگر در شکل یک گزینه جداگانه با نام مناسبت های دیگر ایران افزوده شود
 سپاس
