### ISSUE TITLE
باگ

### ISSUE THREAD

**Issue by kmahdi70** [persian-calendar/DroidPersianCalendar#559]
با سلام و تشکر از برنامه خوبتون. 
یک ایراد داره، اینکه وقتی روز عوض میشه تا وقتی تقویم رو باز نکنیم، روی صفحه موبایل عدد روز تغییر نمیکنه.
 مثلا امروز چهارم هست، فردا همچنان داره چهارم رو روی صفحه نشون میده. همین که تقویم رو باز میکنیم عدد رو به روز میکنه درحالیکه وقتی ساعت ۲۴ میشه باید اتوماتیک عدد روز تغییر کنه. سپاس

**Comment by ebraminio** [comment]
سلام گرامی در تنظیمات گوشی‌های مختلف تنظیمی برای هر برنامه وجود دارد به منظور اجرای برنامه در پیش‌زمینه و استثنا کردن یک برنامه از بهینه‌سازی‌های مصرف باتری

![image](https://user-images.githubusercontent.com/833473/82299438-c4a7db80-99ca-11ea-85dc-04cadecc27f2.png)

کاربران مختلف به من گفته‌اند با اعمال این تنظیمات این مورد برطرف می‌شود، شما هم لطفاً بررسی کنید و من را مطلع کنید، باید راه بهتری می‌داشت و در کل نباید گوشی‌های چنین کنند، اینجا را ببینید

https://dontkillmyapp.com/

ولی این بازی‌های جدید گوشی‌سازان است متأسفانه، ممنونم

**Comment by kmahdi70** [comment]
سلام دوست عزیز
ممنونم از پاسخگوییتون
نه متاسفانه درست نشد
*********************************************************************

*NoorIT.ir <http://noorit.ir/>*
*Karimian 09123238133*
*Web Application Developer*
