### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by pezhi66** [persian-calendar/DroidPersianCalendar#561]
سلام
نوتیفیکیشن روی miui 11 تاریخ رو نشون میداد اما از دیروز که به نسخه ۱۲ ارتقا دادم به جای شماره آیکون برنامه در نوتیفیکیشن نمایش داده میشه
![Screenshot_2020-05-26-13-32-57-046_com android settings](https://user-images.githubusercontent.com/42203105/82881835-76a85000-9f55-11ea-8f8c-e8c1caa23f2f.jpg)

**Comment by ebraminio** [comment]
سلام گرامی، خودتان دارید مشاهده می‌کنید که تغییرات گوشی‌سازان است که چه مشکلاتی به وجود می‌آورد :/ تاجایی که می‌دانم مشکل از آن‌ها و کار زیادی از ما برنمی‌آید، ممنونم
