### ISSUE TITLE
اشتباه در تقویم

### ISSUE THREAD

**Issue by Alijoker79** [persian-calendar/DroidPersianCalendar#562]
در تاریخ 25،26 مهر مصادف با 28،29 صفر اشتباه پیش آمده و به جای 29 صفر 30صفر نوشته شده
با تشکر از شما

**Comment by ebraminio** [comment]
سلام گرامی واقعیت همان زمان بررسی کردم و به نظر درست آمد، شاید تنظیمات تقویم اسلامی را تغییر داده‌اید؟ نسخه‌یتان چیست؟ ممنونم

**Comment by ebraminio** [comment]
در نسخهٔ تنظیم اسلام را پس از ۳۰روز باز می‌گردانم که چنین مشکلاتی پیش نیاید، ممنون :)
