### ISSUE TITLE
اشکال در بروز رسانی روزانه

### ISSUE THREAD

**Issue by mohammadrezasirjani** [persian-calendar/DroidPersianCalendar#565]
در قسمت ناتیفیکیشن بالای موبایل که تاریخ روز رو به شمسی و عددی که اپلیکیشن شما نشون میده گاهی اوقات تاریخ همون تاریخ روز یا روزهای قبل رو نشون میده و با کلیک روی آیکون اَپ از نوار ابزار یا اجرای خود نرم افزار به روز میشه 
لطفا این مشکل رو رفع کنید

**Comment by ebraminio** [comment]
سلام! مشکل از بعضی از این اندرویدهای جدید است ولی معمولاً یک قسمتی دارند مثل این در تنظیمات گوشی برای هر برنامه
![image](https://user-images.githubusercontent.com/833473/85198315-fd561000-b2fc-11ea-9042-83fdde5853ae.png)
که با اجازهٔ اجرا در پیش‌زمینه و استثنا کردن در گزینهٔ بعدی مشکل به‌روزرسانی ظاهراً در بعضی گوشی‌ها برطرف می‌شود، بررسی کنید و ما را مطلع کنید، ممنونم

**Comment by shahinkhorshidfar** [comment]
> در قسمت ناتیفیکیشن بالای موبایل که تاریخ روز رو به شمسی و عددی که اپلیکیشن شما نشون میده گاهی اوقات تاریخ همون تاریخ روز یا روزهای قبل رو نشون میده و با کلیک روی آیکون اَپ از نوار ابزار یا اجرای خود نرم افزار به روز میشه 
> لطفا این مشکل رو رفع کنید

**Comment by shahinkhorshidfar** [comment]
> در قسمت ناتیفیکیشن بالای موبایل که تاریخ روز رو به شمسی و عددی که اپلیکیشن شما نشون میده گاهی اوقات تاریخ همون تاریخ روز یا روزهای قبل رو نشون میده و با کلیک روی آیکون اَپ از نوار ابزار یا اجرای خود نرم افزار به روز میشه 
> لطفا این مشکل رو رفع کنید

- [ ] []()صفحه کلید SwiftKey مایکروسافت
