### ISSUE TITLE
افزودن مناسبت

### ISSUE THREAD

**Issue by profnami** [persian-calendar/DroidPersianCalendar#566]
امروز هفتم تیر سالروز بمباران شیمیایی شهرستان سردشت تنها شهر قربانی مواد شیمیایی در جهان هست ولی این مناسبت در تقویم شما نیست. لطفا این رو هم اضافه کنید.

**Comment by ebraminio** [comment]
سلام گرامی کار تدوین مناسبت‌ها را مرکز تقویم دانشگاه تهران انجام می‌دهد و آن‌ها را در 
https://calendar.ut.ac.ir/Fa/News/Data/Doc/Calendar%201400-Full.pdf
قرار می‌دهد و ما صرفاً آن‌ها را نمایش می‌دهیم و برای مناسبت یجدید باید با آنجا تماس گرفت، ممنون :)
