### ISSUE TITLE
خروج اعلان به محض خروج از برنامه

### ISSUE THREAD

**Issue by habibhoseinpour** [persian-calendar/DroidPersianCalendar#567]
باسلام
قسمت اعلانات وقتی کار میکنه که برنامه درحال اجرا باشه ولی به محض اینکه از برنامه خارج بشوم قسمت اعلانات هم خارج میشه
راه حلش چیه؟
در ضمن گوشیمم شیائومی نوت ۸ هستش

**Comment by AlirezaIvaz** [comment]
الهی الامان از دست شیائومی :/
دیده بودم بعد یه مدت نوتیف بپره اما اینکه فقط موقع باز بودن نوتیف بمونه دیگه عجیبا غریبا!!
ویجت برنامه رو به صفحه اصلی اضافه کنید شاید مشکل حل بشه.

**Comment by ebraminio** [comment]
این راهنما هم شاید مفید باشد

https://github.com/persian-calendar/DroidPersianCalendar/wiki/%D8%A7%D8%B3%D8%AA%D8%AB%D9%86%D8%A7-%DA%A9%D8%B1%D8%AF%D9%86-%D8%AA%D9%82%D9%88%DB%8C%D9%85-%D8%AC%D9%87%D8%AA-%D8%A7%D8%AC%D8%B1%D8%A7%DB%8C-%D8%A8%D9%87%D8%AA%D8%B1-%D8%AF%D8%B1-%D8%A7%D9%86%D8%AF%D8%B1%D9%88%DB%8C%D8%AF%D9%87%D8%A7%DB%8C-%D8%AC%D8%AF%DB%8C%D8%AF

**Comment by habibhoseinpour** [comment]
بازم نشد که نشد 🥺🥺🥺

**Comment by ebraminio** [comment]
ظاهراً یک دکمهٔ قفل کنار برنامه‌ها در لیست برنامه‌های اخیر می‌آورد که باید روی آن کلیک کرد که برنامه را نبندد، شرمنده که از نظر کدی کار خاصی نمی‌توانیم انجام دهیم :/ ممنونم
