### ISSUE TITLE
دکمه غیر فعالسازی ساعت ۲۴ ساعته

### ISSUE THREAD

**Issue by clickmeplz** [persian-calendar/DroidPersianCalendar#569]
کار نمیکنه. همیشه حالت ۲۴ ساعتها فعاله
دستگاه: Xiaomi Mi4

**Comment by ebraminio** [comment]
درست می‌فرمایید گزینهٔ ساعت ۱۲ ساعته به دلایل فنی برای ویجت به راحتی امکان‌پذیر نیست و بیشتر داخل برنامه دیده می‌شود :/

**Comment by ebraminio** [comment]
در نسخهٔ بعد اصلاح می‌شود
https://github.com/persian-calendar/DroidPersianCalendar/commit/e2e029ebb6fcca3bec0c6d2c211348b9533e4f08
ممنون و شرمنده بابت این مدتی که مشکل برطرف نشده بود :)
