### ISSUE TITLE
Just a suggestion and thought for a compass

### ISSUE THREAD

**Issue by bqytallhsirlkm** [persian-calendar/DroidPersianCalendar#572]
Alsalam Alikum,
 after my experience of the application and reading the code for the application, I found that the application is great and thanks a lot to the developers. There is a good thought of the compass, which is the addition of many places such as the shrine of the Prophet Muhammad, may God bless him and his family or the shrine of Ali bin Musa al-Rida or the shrine of Mrs. Fatima almasumah, etc.
So that the user can determine the location in the compass.

Allah Blass you

**Comment by ebraminio** [comment]
Hi and thanks for the suggestion, this leads to have a complicated UI so I rather other more specific apps to offer the feature. Thanks and let us know other suggestions you got. Thanks!
