### ISSUE TITLE
عریض شدن ناتیفیکیشن

### ISSUE THREAD

**Issue by irmacfa** [persian-calendar/DroidPersianCalendar#573]
![Screenshot_20200723-233233](https://user-images.githubusercontent.com/9676983/88327979-017eae80-cd3d-11ea-92c4-34177c29ba0a.png)

تسک بار منو این شکلی شده
تو اندروید 10

**Comment by ebraminio** [comment]
سلام! عــــجب، اگه گوشی رو تو حالت تاریک ببرید فرقی می‌کنه آیا؟ اولین بار هست همچین چیزی می‌بینم :/

**Comment by irmacfa** [comment]
> سلام! عــــجب، اگه گوشی رو تو حالت تاریک ببرید فرقی می‌کنه آیا؟ اولین بار هست همچین چیزی می‌بینم :/

روی حالت تاریک مشکلی نداره

![Screenshot_20200724-000738](https://user-images.githubusercontent.com/9676983/88331193-d34f9d80-cd41-11ea-9e42-c374200220a8.png)

**Comment by irmacfa** [comment]
سلام مجدد این مشکل در فضای سفید تکرار شد همچنان عریض شد

**Comment by ebraminio** [comment]
واقعیت نمی‌دونم :/

**Comment by irmacfa** [comment]
> واقعیت نمی‌دونم :/

یه مدت خوب شد
 ولی باز امروز از صبح روی اندروید 10 پا برجا شد

![Screenshot_20200815-231738](https://user-images.githubusercontent.com/9676983/90319502-01de2400-df4e-11ea-8b2d-774e53415b40.png)

**Comment by ebraminio** [comment]
حدس می‌زنم مشکل از تنظیم اعلان‌های کاستام هست که در تم تاریک غیرفعال است

https://github.com/persian-calendar/DroidPersianCalendar/blob/master/PersianCalendar/src/main/java/com/byagowi/persiancalendar/utils/UpdateUtils.kt#L464-L510

shouldDisableCustomNotification با تم تاریک غیر فعال می‌شود

منتهی نباید اینجوری باشه :/

**Comment by irmacfa** [comment]
مهندس رفع شد. ممنون

**Comment by ebraminio** [comment]
چگونه برطرف شد، در بیلد شخصی؟ کاش می‌شد با نگه داشتن آن خاصیت این کارو کرد؟

**Comment by irmacfa** [comment]
> چگونه برطرف شد، در بیلد شخصی؟ کاش می‌شد با نگه داشتن آن خاصیت این کارو کرد؟

همین الان خود به خود

**Comment by erfanva** [comment]
برای منم این مشکل بعضی موقع ها ایجاد میشه. اندرویدم ۱۰ و وان عه. دارم مود هم هستم.
برای درست کردنش فورس استاپ می‌کنم و دوباره اپ رو باز می‌کنم.

**Comment by ebraminio** [comment]
https://github.com/persian-calendar/DroidPersianCalendar/commit/50e98e51dba674638f2f8526cdf744eb45cc318c
این تغییر را اعمال کردم که شاید با آن برطرف شود، کاش می‌شد آن را به اندازهٔ خوبی تست کرد

**Comment by ebraminio** [comment]
تاجایی که می‌دانم باید این مشکل را برطرف کرده باشم، لطفاً در نسخه‌های اخیر بررسی کنید، ممنونم :)
