### ISSUE TITLE
پخش نشدن اذان در اندروید۱۰

### ISSUE THREAD

**Issue by Masih-Zehtab** [persian-calendar/DroidPersianCalendar#574]
اندروید کاستوم اپن سورس.ذام رسمی
وقتی صفحه ققل میشه و هنگام اذان باشه قادر به اجرا نیست

**Comment by ebraminio** [comment]
فکر می‌کنم در نسخهٔ اخیر بهتر شده باشد که اصلاحی در این رابطه داشته‌ایم، لطفاً بررسی فرمایید، ممنونم :)

**Comment by shahinkhorshidfar** [comment]
> اندروید کاستوم اپن سورس.ذام رسمی
> وقتی صفحه ققل میشه و هنگام اذان باشه قادر به اجرا نیست
