### ISSUE TITLE
پخش اذان درست نیست

### ISSUE THREAD

**Issue by molkmaik** [persian-calendar/DroidPersianCalendar#578]
برنامه زمان اذان را درست نشان میدهد اما با یک دقیقه تاخیر اذان پخش میکند. مثلا اذان ۸:۰۶  را نشان میدهد اما ساعت ۸:۰۷ اذان پخش میکند

**Comment by AlirezaIvaz** [comment]
سلام.
اونجور که من حدس می‌زنم اینه که ثانیه هم محاسبه می‌شه و به‌خاطر همین بعضی‌وقتا چند ثانیه حتی تا ۵۹ ثانیه دیرتر اذان پخش می‌شه.
البته اینجوری حدس می‌زنم چون برای خودم این مدت هر دفعه تغییر می‌کنه.
اگه واقعا این‌جوری باشه، این یه برتری در برابر باد صبا خواهد بود.
البته ممکن هم هست که اینجوری نباشه و یه باگ باشه :)

**Comment by molkmaik** [comment]
سلام ظاهرا اشکال برنامه است چون هیچ قانونی ندارد. گاهی زودتر اذان میگه گاهی 
دیرتر. نه تنها با باد صبا بلکه با اذان رادیو تلویزیون هم مطابقت ندارد

**Comment by ebraminio** [comment]
در نسخهٔ اخیر کمی بهتر شده زیرا ثانیه را صفر نمی‌کردیم، ممنونم :)
