### ISSUE TITLE
مشکل در نمایش Notification

### ISSUE THREAD

**Issue by esijon66** [persian-calendar/DroidPersianCalendar#583]
من چندین ساله از این برنامه استفاده میکنم و طی آپدیت های  اخیر مشکلی که پیدا کرده این هست ، تاریخی که در قیمت نوتیفیکیشن نمایش داده میشه بعضی وقتها آپدیت نمیشه و باید روش بزنیم تا آپدیت بشه

گوشی من huawei nova3 هست

**Comment by ebraminio** [comment]
سلام گرامی ظاهراً آپدیت‌های جدید اندروید در بعضی گوشی‌ها کاربر را مجبور می‌کند که چنین تنظیماتی که در لینک روبرو آمده را اعمال کند

https://github.com/persian-calendar/DroidPersianCalendar/wiki/%D8%A7%D8%B3%D8%AA%D8%AB%D9%86%D8%A7-%DA%A9%D8%B1%D8%AF%D9%86-%D8%AA%D9%82%D9%88%DB%8C%D9%85-%D8%AC%D9%87%D8%AA-%D8%A7%D8%AC%D8%B1%D8%A7%DB%8C-%D8%A8%D9%87%D8%AA%D8%B1-%D8%AF%D8%B1-%D8%A7%D9%86%D8%AF%D8%B1%D9%88%DB%8C%D8%AF%D9%87%D8%A7%DB%8C-%D8%AC%D8%AF%DB%8C%D8%AF

لطفاً بررسی کنید و ما را مطلع کنید، ممنونم :)
