### ISSUE TITLE
پخش اذان

### ISSUE THREAD

**Issue by Mohammad-Samini** [persian-calendar/DroidPersianCalendar#584]
ضمن عرض سلام
با وجود اینکه نرم‌افزار بسیار عالی، ساده و شیک طراحی شده و تأکید می‌کنم که بسیار ساده است اما در گوشی من 
A70
که مبتنی بر 
Android 10
است، اذان پخش نمی‌شود.
راهنمایی در مورد تغییر در تنظیم‌های گوشی هم کمک نکرده است.
لطفاً این مشکل را حل بفرمایید.

**Comment by ebraminio** [comment]
سلام گرامی این راهنما رو بررسی فرمایید
https://git.io/JUazN
احتمال دارد مشکل را برطرف کند، ممنونم :)

**Comment by Mohammad-Samini** [comment]
طی سه بار که خدمت شما پیام داده‌ام، همین راهنمایی ارسال شده است!
من مجبور شده‌ام اذانگو
<https://play.google.com/store/apps/details?id=com.salman.azangoo&hl=fa> را
هم برای پخش اذان فعال کنم در حالی‌که همان‌طور که قبلاً هم نوشته‌ام به‌خاطر
سادگی مایلم از برنامهٔ شما استفاده کنم.
ان‌شاءالله که بتوانید مشکل را حل بفرمایید.


‫‪ebraminio‬‏ <‪notifications@github.com‬‏> در تاریخ چهارشنبه ۱۴ اکتبر ۲۰۲۰
ساعت ۲۱:۰۹ نوشت:‬

**Comment by ebraminio** [comment]
در نسخهٔ جدید کمی بهبود در این رابطه اعمال شده، امیدوارم هنوز این برنامه استفاده کنید، امکان دارد اذان را دوباره بررسی کنید؟ ممنون :)

**Comment by Mohammad-Samini** [comment]
سلام و درود بر شما
بله من هنوز از برنامهٔ شما استفاده می‌کنم. حتی در اندروید داخل ماشینم!
اما خیر متأسفانه خبری از پخش اذان نیست.
فقط هشدار اذان رو که فعال کردم... صدایی مثل رسیدن پیامک پخش می‌شود.. که
آن‌هم با چند دقیقه تأخیر است.

با احترام،
محمد ثمینی

‫‪ebraminio‬‏ ***@***.***‬‏> در تاریخ چهارشنبه ۱۵ سپتامبر
۲۰۲۱ ساعت ۲:۱۴ نوشت:‬

**Comment by Mohammad-Samini** [comment]
پیرو ایمیل قبلی
الان دوباره برنامه رو ریست کردم
فکر کردم شاید چون من اذان اردبیلی رو انتخاب کرده بودم، مشکل پیش اومده بود.
حالا ببینم که وضعیت چه می‌شود، خدمتتون خواهم نوشت.
گوشی من a70 است.

در تاریخ چهارشنبه ۱۵ سپتامبر ۲۰۲۱،‏ ۰۲:۱۴ ebraminio <
***@***.***> نوشت:

**Comment by Mohammad-Samini** [comment]
پیرو دو ایمیل قبلی، اولین اذان مغرب رو شنیدم! با تقریبا یک دقیقه تأخیر.
تا چند اذان دیگه هم بشنوم و ان‌شاءالله این برنامه از نظر بخش اذان اصلاح شده
باشه.
گرچه اذان ملی ما مؤذن‌زاده اردبیلی رو نداره!
از ایمیل شما و آگاهی‌رسانی شما سپاسگزارم.

در تاریخ چهارشنبه ۱۵ سپتامبر ۲۰۲۱،‏ ۰۲:۱۴ ebraminio <
***@***.***> نوشت:

**Comment by Mohammad-Samini** [comment]
پیرو سه ایمیل پیشین، باید به اطلاع شما برسانم که طی ۲۴ ساعت گذشته، برنامهٔ
شما سر وقت اذان را پخش کرده است.
خیلی سپاسگزارم.
اگر ممکن بود، اذان کامل مؤذن‌زاده را نیز اضافه بفرمایید.

با احترام،
محمد ثمینی

‫‪ebraminio‬‏ ***@***.***‬‏> در تاریخ چهارشنبه ۱۵ سپتامبر
۲۰۲۱ ساعت ۲:۱۴ نوشت:‬

**Comment by ebraminio** [comment]
ممنونم جناب ثمینی :) من ایمیل‌هایتان را دنبال می‌کردم و خوشحالم که مشکل برطرف شده است، برای صدای اذان کمی محدودیت در مسألهٔ حق تکثیر و سایر جزئیات داشته‌ایم به همین دلیل انتخاب اذان را به عهده کاربر قرار داده‌ایم، ممنونم :)
