### ISSUE TITLE
امکان حذف تقویم قمری در ویجت

### ISSUE THREAD

**Issue by ebinem173** [persian-calendar/DroidPersianCalendar#596]
سلام خسته نباشید
لطفا در صورت امکان
قابلیت حذف تقویم قمری رو در ویجت قرار بدید
با تشکر

**Comment by hmasroor** [comment]
کلاً شخصی سازی ویجت ها داغونه منم امکان حذف کامل اذان از ویجت ها رو میخوام

**Comment by ebraminio** [comment]
سلام، ممنون، امکان حذف قمری از کل برنامه وجود دارد و تنظیم خاص برای ویجت کمی بعید می‌رسید انجام دهیم، برای حذف اذان از ویجت ۴در۲ باگ دیگری وجود به همین دلیل این باگ را می‌بندم، ممنونم :)
