### ISSUE TITLE
اشتباه بودن زمان باقی‌ماندهٔ ویجت

### ISSUE THREAD

**Issue by zokayi** [persian-calendar/DroidPersianCalendar#602]
![Screenshot_20201215-185214_One UI Home](https://user-images.githubusercontent.com/63492616/102234839-f05e5600-3f06-11eb-9d58-ed0093999073.png)
زمان باقیمانده به اذان اشتباه است

**Comment by ebraminio** [comment]
تقریباً امیدی به اصلاح شدن زمان باقی‌مانده نیست :/ به همین دلیل آن را با مناسبت‌های روز جایگزین کرده‌ام برای نسخهٔ بعد
