### ISSUE TITLE
key که ساین شده برنامه تو سورس هست

### ISSUE THREAD

**Issue by n-khosh** [persian-calendar/DroidPersianCalendar#606]
سلام ، key ای که برای ساین استفاده کردین تو سورس هست حتی رمز رو هم تو گرادل گذاشتین ، بنظرم این موارد نباید پوش بشن

**Comment by runo280** [comment]
سلام اون کلید صرفا برای انتشار خودکار یه نسخه شبانه از ‍‍پروژه هست که توی کانال زیر در تلگرام منتشر میشه
https://t.me/Persian_Calendar
پکیج نیم هم متفاوته
