### ISSUE TITLE
اشتباه در تعطیلی

### ISSUE THREAD

**Issue by mahmoodesk** [persian-calendar/DroidPersianCalendar#608]
روز 26/11 تعطیل نیست زده تعطیل
لطفا درستش کنید

**Comment by ebraminio** [comment]
سلام گرامی عکسی تهیه می‌فرمایید؟ اینجا که اینگونه نبوده، ممنونم

**Comment by ebraminio** [comment]
احتمالاً از تنظیمات رخصتی‌های افغانستان (تعطیلی‌های کشور افغانستان) را فعال کرده‌اید، در صورت غیرفعال کردن آن درست می‌شود، لطفاً آزمایش فرمایید، ممنونم :)
