### ISSUE TITLE
درخواست امکان حذف اذان از ویجت 2 در 4

### ISSUE THREAD

**Issue by hmasroor** [persian-calendar/DroidPersianCalendar#609]
سلام
به نظر من بهترین ویجت 2 در 4 بزرگترینه هست اما من به بخش اذانش نیاز ندارم.
ولی حتی اگر اذان رو در تنظیمات غیرفعال کرده باشم بازم بخشش در این ویجت به صورت خط تیره نمایش داده میشه.
امکان تنظیم اندازه ارتفاع ویجت هم بستید و نمیشه مثلاً ارتفاعش رو کم کرد تا اذان پاک بشه.

لطفاً امکان حذف کامل اذان از تمامی ویجت ها الخصوص 2 در 4 را اضافه فرمایید.
با تشکر از برنامه خوبتون.

**Comment by hmasroor** [comment]
منظورم ویجت داخل این عکسه که دوست دیگه ای در تاپیک خودشون گذاشتن:
https://user-images.githubusercontent.com/63492616/102234839-f05e5600-3f06-11eb-9d58-ed0093999073.png

**Comment by runo280** [comment]
میخواستم تغییر سایز رو پیشنهاد بدم که دیدم نوشتید ممکن نیست، ولی اتفاقا جلوش رو [نبستیم](https://github.com/persian-calendar/DroidPersianCalendar/blob/67a9f96d9dfcf5eb65146284db79efd603fa2ef9/PersianCalendar/src/main/res/xml/persiancalendar_provider4x2.xml#L9)، من  خودم از همین روش استفاده کردم و از لانچر زیر استفاده میکنم:
Nova

**Comment by ebraminio** [comment]
انجام شد، با تشکر بابت پیشنهاد :)
