### ISSUE TITLE
ناتیفیکیشن

### ISSUE THREAD

**Issue by kiahmg89** [persian-calendar/DroidPersianCalendar#611]
سلام و عرض ادب ..
آقا ما نصبش کردیم اما عددش نیومده تو ناتیفیکیشن .. مدل گوشی هم huawie - nova 7i

**Comment by ebraminio** [comment]
سلام گرامی، اگر تازه نصب کرده‌اید، فکر می‌کنم تنظیمات برنامه‌ها در گوشی یک تنظیمی مربوط به این دارد که اعلان دیده شود که آنجا در گوشی شما فکر می‌کنم پیش‌فرض غیرفعال است، یک نگاهی بیندازید، ممنون :)

**Comment by kiahmg89** [comment]
سلام بله نگاه کردیم اما اینطور نبود .. منویی هم پیدا نکردیم که داشته باشه برای این موضوع ..از داخل سیستم عامل هم ناتیفیکیشن برای این برنامه روشن بود اما مشکل همچنان وجود داشت . ممنونم اکر با عکس به ما نشان دهید که چکار کنیم .   Sent from Mail for Windows 10 From: ebraminioSent: ‏چهارشنبه,‏ ‏6 ‏اسفند ‏1399 ‏10:09 ‏ب.ظTo: persian-calendar/DroidPersianCalendarCc: kiahmg89; AuthorSubject: Re: [persian-calendar/DroidPersianCalendar] ناتیفیکیشن (#611) سلام گرامی، اگر تازه نصب کرده‌اید، فکر می‌کنم تنظیمات برنامه‌ها در گوشی یک تنظیمی مربوط به این دارد که اعلان دیده شود که آنجا در گوشی شما فکر می‌کنم پیش‌فرض غیرفعال است، یک نگاهی بیندازید، ممنون :)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ebraminio** [comment]
داخل برنامه هم تنظیم اعلان روشن است؟ واقعیت خودم گوشی هواوی نداشتم نمی‌دونم ولی دیدم این گوشی‌ها یه تنظیماتی برای اعلان گذاشته‌اند که از برنامه‌هایی که پوش‌نوتیفیکیشن و این‌ها دارند برای کاربر مزاحمت ایجاد نکنند که تقویم فارسی دسترسی به اینترنت ندارد چه برسد این‌ها ولی خب ظاهراً بازم تنظیمش را می‌خواهد

**Comment by ebraminio** [comment]
تقریباً از داخل برنامه کاری نیست که بشود در رابطه با این مورد انجام داد ولی راهنمای
https://dontkillmyapp.com/huawei 
را حتماً مشاهده فرمایید، ممنونم
