### ISSUE TITLE
Isn't the 30th of Esfand a Holiday?

### ISSUE THREAD

**Issue by molaeiali** [persian-calendar/DroidPersianCalendar#612]
I think the 30th of Esfand is a holiday, but it's not on the calendar

**Comment by ebraminio** [comment]
سلام، اینجا که چیزی نیامده؟
https://calendar.ut.ac.ir/Fa/News/Data/Doc/Calendar%201399-Full.pdf

**Comment by molaeiali** [comment]
جالبه سال ۹۵ وزارت رفاه نامه داشته راجع بهش و تو قانون گفته شده ۲۹ تا ۴ فروردین تعطیله که ۳۰م هم توشه

[خبرآنلاین - ۳۰ اسفند تعطیل رسمی شد](https://www.khabaronline.ir/news/639321/%DB%B3%DB%B0-%D8%A7%D8%B3%D9%81%D9%86%D8%AF-%D8%AA%D8%B9%D8%B7%DB%8C%D9%84-%D8%B1%D8%B3%D9%85%DB%8C-%D8%B4%D8%AF)

[خبرگزاری مهر - ۳۰ اسفند برای مشمولان قانون کار تعطیل رسمی شد](https://www.mehrnews.com/news/3914351/%DB%B3%DB%B0-%D8%A7%D8%B3%D9%81%D9%86%D8%AF-%D8%A8%D8%B1%D8%A7%DB%8C-%D9%85%D8%B4%D9%85%D9%88%D9%84%D8%A7%D9%86-%D9%82%D8%A7%D9%86%D9%88%D9%86-%DA%A9%D8%A7%D8%B1-%D8%AA%D8%B9%D8%B7%DB%8C%D9%84-%D8%B1%D8%B3%D9%85%DB%8C-%D8%B4%D8%AF)

[خبرگزاری تسنیم -  ۳۰ اسفند تعطیل رسمی شد ](https://www.tasnimnews.com/fa/news/1395/12/04/1335880/30-%D8%A7%D8%B3%D9%81%D9%86%D8%AF-%D8%AA%D8%B9%D8%B7%DB%8C%D9%84-%D8%B1%D8%B3%D9%85%DB%8C-%D8%B4%D8%AF)

![Image](https://newsmedia.tasnimnews.com/Tasnim/Uploaded/Image/1395/12/04/13951204105452194100786110.jpg)

**Comment by molaeiali** [comment]
اینم راستی توی سایت مجلسه گویا
https://rc.majlis.ir/fa/law/show/99002

گفته شده ۲۹ تا ۴ که خب ۳۰م هم توشه

**Comment by ebraminio** [comment]
اگر خبری از مرکز تقویم دریافت کردید حتماً ما را مطلع کنید که دقیقاً عنوان این تعطیلی چه باید باشد، ممنونم :)
