### ISSUE TITLE
پیشنهاد فونت و وسط چین شدن اعلان

### ISSUE THREAD

**Issue by iranabst** [persian-calendar/DroidPersianCalendar#613]
ضمن تبریک بابت توسعه بهترین تقویم پارسی اندروید
در صورت امکان موارد زیر مورد توجه توسعه دهندگان عزیز قرار گیرد 
مورد اول : وسط چین شدن اعلان 
مورد دوم : افزودن فونت های زیبا و رایج ایران سنس ، ایران یکان و دیگر موارد
مورد سوم : گرد کردن گوشه های ویجت

**Comment by ebraminio** [comment]
> مورد سوم : گرد کردن گوشه های ویجت

این مورد انجام شد برای نسخهٔ بعد :)

<img width="268" alt="image" src="https://user-images.githubusercontent.com/833473/133678929-d9aae7b9-a753-4b56-b12d-4f4ffdd4988a.png">

> مورد اول : وسط چین شدن اعلان

تلاشمون این هست که ظاهر گوشی تاجای ممکن حفظ بشه به خاطر همین بعیده همچین کاری انجام بشه واقعیت

> مورد دوم : افزودن فونت های زیبا و رایج ایران سنس ، ایران یکان و دیگر موارد

ادغام در #592

ممنونم :)
