### ISSUE TITLE
اضافه کردن مناسبت های ایرانی

### ISSUE THREAD

**Issue by f628ms** [persian-calendar/DroidPersianCalendar#614]
درود فراوان
چهارشنبه‌سوری در تقپیم ۱۳۹۹ نیست !
سالگرد بمباران شیمیایی حلبچه

**Comment by ebraminio** [comment]
درود گرامی، مناسبت‌ها با 
https://calendar.ut.ac.ir/Fa/News/Data/Doc/Calendar%201400-Full.pdf
انطباق دارد، در رابطه با مورد دوم آیا از تنظیمات سایر مناسبت‌ها را فعال کرده‌اید؟ ممنونم
