### ISSUE TITLE
اضافه کردن تست اذان توی تنظیمات قسمت اذان

### ISSUE THREAD

**Issue by amirmahdi-nsh** [persian-calendar/DroidPersianCalendar#615]
<p dir='rtl' align='right'>
سلام و خسته نباشید، درخواستم اینه در آخر تنظیمات اذان یه گزینه اضافه بشه که یه پیش‌نمایش از اذان رو نشون بده. این خیلی چیز خوبیه وقتی که کاربر تنظیمات رو عوض میکنه و میخواد به نگاه کلی بندازه که شکل اذان چطوری شده.
</p>
<p dir='rtl' align='right'>
بعد چیز دیگه اینکه من داشتم توی کد برنامه گشت می‌زدم که به یه چیزی برخوردم، فهمیدم که اگه روی تب «اوقات شرعی» واقع توی صفحه‌ی اصلی کلیک کنم و روی نام شهر نگه دارم همین اتفاق میوفته و یه پیش‌نمایشی از اذان نشون میده در صورتی که هم جای قرارگیری این ویژگی توی تنظیمات بهتر بود و هم اینکه هیچ جایی توی راهنماها به این موضوع اشاره‌ای نشده
</p>
ممنونم

**Comment by ebraminio** [comment]
<div dir=rtl>
سلام گرامی، پیشنهاد جالبی است، و خیلی جالب که آن قابلیت را پیدا کردید :) به گونه‌ای صرفاً برای آزمایش اضافه شده است به همین دلیل بوده که جایی دربارهٔ چیزی نوشته نشده است.
</div>

**Comment by amirmahdi-nsh** [comment]
<p dir='rtl' align='right'>
ببخشید که وقت ندارم وگرنه خودم درست میکردم و pull request میزدم :)
<p/>

<p dir='rtl' align='right'>
اگه هم شما هم یکم مشغله‌تون زیاده اگه دوست داشتین به بقیه‌ی مشکلات برنامه برسین و منم آروم آروم این قابلیت رو پیاده‌سازی میکنم
<p/>

**Comment by ebraminio** [comment]
<div dir=rtl>
اوه، اگه خودتون بخواید انجام بدید مشکلی واسه اعمال نداره :)
</div>

**Comment by amirmahdi-nsh** [comment]
<p dir='rtl' align='right'>
واقعا منو ببخشید. کد رو بررسی کردم ولی چون جزو اولین کارهایی هست که با kotlin و java انجام میدم در خیلی از قسمت‌ها نمی‌دونم به چه صورت باید کار بشه(یا اینکاری که دارم میکنم اصولی هست یا نه). اگه امکانش هست خودتون پیاده‌سازیش کنید. خیلی ممنونم
</p>

**Comment by ebraminio** [comment]
مشکلی نیست گرامی اتفاقاً برای تغییراتی که اواخر انجام دادم اگر وجود می‌داشت کارم را خیلی راحت می‌کرد :)
