### ISSUE TITLE
نمایش تعداد هفته سال در روز ۳۰اسفند

### ISSUE THREAD

**Issue by alidtaba** [persian-calendar/DroidPersianCalendar#616]
سلام و وقت بخیر
چرا تعداد هفته از ابتدای سال رو ۵۴ تا داره نمایش میده؟
![Screenshot_20210320-085539]
(https://user-images.githubusercontent.com/11313195/111860181-10187680-895b-11eb-8784-1cb0d0f0a974.png)

**Comment by ebraminio** [comment]
سلام، یه فرمول ساده‌ای داره که تو تقویم بهش رسیدیم از رو اون محاسبه می‌شه

https://github.com/persian-calendar/DroidPersianCalendar/blob/b145aa0035d0066da09094b6b1f977fd541d3681/PersianCalendar/src/main/java/com/byagowi/persiancalendar/utils/CalendarUtils.kt#L50

اگه پیشنهادی داشتید حتماً مطرح کنید، ممنونم :)

**Comment by alidtaba** [comment]
دم شما گرم

**Comment by ebraminio** [comment]
🙏🙏
