### ISSUE TITLE
عدم بروز رسانی

### ISSUE THREAD

**Issue by dichopra** [persian-calendar/DroidPersianCalendar#617]
سلام و احترام فراوان
ممنون و خداقوت بخاطر برنامه ی خیلی خوب و جامع و عالی تان،
متاسفانه تنها اشکال برنامه برای گوشی من عدم بروزرسانی تاریخ برنامه بعد از ساعت ۲۴ می باشد

**Comment by ebraminio** [comment]
سلام گرامی گوشتان چیست؟ این مشکل معمولاً در بعضی از برندهای خاص اتفاقی میافتد که راه‌حلی برایش نداشته‌ایم،

https://github.com/persian-calendar/DroidPersianCalendar/wiki/استثنا-کردن-تقویم-جهت-اجرای-بهتر-در-اندرویدهای-جدید

را نگاهی بیاندازید و حتماً ما را از نتیجه مطلع کنید، ممنون :)

**Comment by dichopra** [comment]
ZenFone 3 Zoom (ZE553KL) | Phone | ASUS Global
سلام ممنون تغییرات رو الان انجام دادم فردا نتیجه اش را خدمتتان اعلام خواهم
کرد سپاسگزارم

**Comment by dichopra** [comment]
سلام و عرض ادب
متاسفانه با تغییراتی که فرمودید نتیجه ای حاصل نشد متشکرم

**Comment by ebraminio** [comment]
یک نگاهی بیاندازید ببینید توضیحات اضافی
https://dontkillmyapp.com/asus
تأثیری خواهد داشت، اگه نه که نمی‌دانم واقعیت :/
