### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by john2020star** [persian-calendar/DroidPersianCalendar#621]
You have specified android:gradientRadius in an integer value of level_2d.xml and bubble_2d.xml

As stated https://stackoverflow.com/questions/27384655/android-gradient-on-lollipop-not-working-api-21, such a value can cause a bug in API Level 21, change it to the float or dimensional data format.

**Comment by ebraminio** [comment]
Thank you for the heads up! This is a very non essential part of the app and as we don't care that much about those old APIs I went with percentage values in 884fd11 which hopefully gives more reliable result on newer devices. Thanks!

**Comment by ebraminio** [comment]
Btw, curios to know how you found the project and the issue? :) Thanks!

**Comment by john2020star** [comment]
We have an automatic tool that can scan for such kind of compatibility issues in XML. I found your project in FDroid
________________________________
