### ISSUE TITLE
Some events appear on the wrong day

### ISSUE THREAD

**Issue by barudaret** [persian-calendar/DroidPersianCalendar#633]
This event should appear on شنبه, but appears on جمعه instead.  I'll happily attach ICS file if asked, but github doesn't allow ICS files.  What file hosting service is preferred?

![Screenshot_۲۰۲۱۰۴۱۳-۰۸۵۴۵۶_Persian Calendar_1](https://user-images.githubusercontent.com/32847759/114583236-408bc180-9c36-11eb-8ea9-739f31067059.jpg)
![image26](https://user-images.githubusercontent.com/32847759/114584617-b6445d00-9c37-11eb-81b5-fe6d5f183268.png)

**Comment by ebraminio** [comment]
سلام گرامی در تقویم دستگاه چه نشان می‌دهد؟ ما مستقیم از تقویم دستگاه می‌پرسیم و حدسم تفاوت ناحیهٔ زمان رویداد تنظیم شده و دستگاه است که احتمالاً برای تقویم دستگاهتان نیز چنین مشکلی داشته باشد، ممنونم

**Comment by barudaret** [comment]
چطور بررسی کنم؟  در اپ پیش فرض سَمسانگ؟
![Screenshot_20210413-174056_Calendar_1](https://user-images.githubusercontent.com/32847759/114638305-2a0a5800-9c80-11eb-854a-4c1192c9bada.jpg)

ناحیه زمان «Mountain Standard» است

**Comment by ebraminio** [comment]
درست است همین که کجای جدول تقویم اصلی گوشی آن را نشان می‌دهد، مایل بودید فایل تقویم این رویداد را کافی است در زیپ بگذارید تا اینجا بارگذاری شود، آیا در تنظیمات گزینهٔ به ساعت ایران را فعال کرده‌اید؟

**Comment by ebraminio** [comment]
ایشو را می‌بندم ولی همچنان می‌توانید پیام دهید، ممنونم :)

**Comment by barudaret** [comment]
ببخشید.  این را ندیدم.

[5th Saturday of Lent The Akathist Hymn 7936258199086143177.ics.zip](https://github.com/persian-calendar/DroidPersianCalendar/files/6345256/5th.Saturday.of.Lent.The.Akathist.Hymn.7936258199086143177.ics.zip)

«آیا در تنظیمات گزینهٔ به ساعت ایران را فعال کرده‌اید؟»

نه. باید من؟

**Comment by maemunman** [comment]
وای، فعال کردم، و حالا رویداد در روز درست است

**Comment by ebraminio** [comment]
نباید اینطوری باشه :/ این فایلی که فرستادید هم به نظر درسته، باید ببینم مشکل از کجاس، ممنونم :)
