### ISSUE TITLE
droid persian calendar lib?

### ISSUE THREAD

**Issue by lrhm** [persian-calendar/DroidPersianCalendar#634]
first of all, is there a library of this awesome project?
it would be really nice if there is lib tools for parsing and converting dates, something like moment-jalaali. 
another nice thing would be a CalendarView. what do you thing about these? think it's easy to extract this libs from this project?

**Comment by ebraminio** [comment]
سلام گرامی واقع‌گرایانه بعیده در قالب این پروژه به این زودی اتفاق بیافته که یکی از دلایل مجوز جی‌پی‌ال که کتابخانه‌هایی که از چنین کتابخانه‌ای استفاده می‌کنند را ملزم به داشتن مجوز هماهنگ و دیگری ملزوماتی که یک برنامه چندزبانه با دسترسی‌پذیری برای پیاده‌سازی‌ها ایجاد کرده‌اند، ممنونم :)
