### ISSUE TITLE
گزارش اشکال

### ISSUE THREAD

**Issue by Matryoshka85** [persian-calendar/DroidPersianCalendar#635]
سلام، وقت بخیر

در آپدیت جدید در قسمت تبدیل تاریخ، بعد از وارد کردن تاریخ مورد نظر، فقط معادل تاریخ قمری و میلادی نشان داده می‌شود و معادل تاریخ شمسی حذف شده. خواهشمندم این مشکل را رفع نمایید.
با تشکر از زحمات شما

**Comment by ebraminio** [comment]
مشکل تأیید شد، تا رفع مشکل رلیز جدید متوقف شد

**Comment by ebraminio** [comment]
رلیز متوقف شد، مشکل را برطرف کردم و مجبورم رلیز جدیدی چند روز دیگه ارائه دهم، اگر تا آن موقع نسخه‌ای می‌خواستید که دچار این مشکل نباشد لطفاً مرا مطلع کنید، ممنونم :)
