### ISSUE TITLE
اضافه کردن تم سیاه (امولد)

### ISSUE THREAD

**Issue by Mahdi0620** [persian-calendar/DroidPersianCalendar#647]

**Comment by ebraminio** [comment]
موضوع جالبیست که قبلاً روش فکر هم کرده بودم که می‌خواستم تم تاریک فعلی رو بهش نزدیک کنم، ممنون که مطرح کردید و احتمالاً راهش همون اضافه کردن تم دیگری باشد

**Comment by ebraminio** [comment]
نسخه‌ای که چند روز پیش منتشر شده شامل این تم هست، حتماً بررسی کنید و در صورت اصلاح برای نسخهٔ بعد بفرمایید :)
