### ISSUE TITLE
اشکال در ۱۵ مرداد ۱۴۰۰

### ISSUE THREAD

**Issue by Oldman1982** [persian-calendar/DroidPersianCalendar#691]
توی رویدادهای ۱۵ مرداد اینگونه سه مورد رخداد نوشته شده ، اصلاح بشه

انفجار بمب اتمی آمریکا در هیروشیما با بیش از ۱۶۰هزار کشته و مجروح در سال ۱۹۴۵ میلادی (۱۵ مرداد)
سالروز شهادت امیر سرلشکر خلبان عباس بابایی (۱۳۶۶ ه‍.ش) (۱۵ مرداد)
گاهنبار میدیوشِم، جشن میانهٔ تابستان (۱۵ مرداد)
انفجار بمب اتمی آمریکا در هیروشیما با بیش از ۱۶۰ هزار کشته و مجروح (۱۹۴۵ میلادی) (۶ اوت)

**Comment by ebraminio** [comment]
با تشکر اعمال شد :)
