### ISSUE TITLE
مشکل در ارتفاع قسمت مناسبت‌ها

### ISSUE THREAD

**Issue by eshagh79** [persian-calendar/DroidPersianCalendar#692]
سلام
ممنون از برنامه عالیتون
هنگام جابه‌جای به بخش مناسبت‌ها ارتفاع آن قسمت تازه سازی نمیشود.

طریقه ایجاد:
۱. برنامه تقویم رو باز کنید
۲. از کادر پایین روی تب تقویم کلیک کنید
۳. از برنامه خارج شوید و دوباره آن را باز کنید
۴. بعد از بازکردن اینبار از کادر پایین روی تب مناسبت‌ها کلیک کنید
نکته: باید روزی رو انتخاب کنید که مناسبت های زیادی داشته باشه تا مشکل قابل دیدن باشه، مثل امروز
اگه تو مرحله دوم روی تب مناسبت‌ها کلیک کنید این اتفاق نمی‌افته

گوشیم سامسونگ گرند پرایم، اندروید ۵
نسخه برنامه تقویم: ۶.۶.۲
![Screenshot_۲۰۲۱-۰۸-۰۶-۱۱-۴۹-۳۵](https://user-images.githubusercontent.com/52137191/128474672-1c0387f7-0b7a-4006-931b-9998b12f1955.png)
![Screenshot_۲۰۲۱-۰۸-۰۶-۱۱-۴۹-۴۵](https://user-images.githubusercontent.com/52137191/128474684-817fc9ae-6b83-4d1f-8ec4-8fcc318e228f.png)

**Comment by ebraminio** [comment]
گزارش اشکال عالی بود خصوصاً که مراحل را دقیق یادداشت کرده‌اید، دارم سعی می‌کنم ببینم کاری می‌شود کرد، ممنونم :)

**Comment by ebraminio** [comment]
و فعلاً با چند ساعت بررسی به راه‌حلی نرسیدم :)

**Comment by eshagh79** [comment]
خسته نباشید. ممنون که وققتتون رو میزارید.
اصلا تونستید این مشکل رو برای خودتون ایجاد کنید؟
شاید مربوط به اندروید گوشی من یا ارتفاع گوشی من باشه.

متاسفانه منم ابزار لازم برای ساختن و بررسی کد رو ندارم وگرنه کمک میکردم

**Comment by ebraminio** [comment]
بله مشکل را همان اول با توضیح خوبتون دیدم :) نه مربوط به دستگاه خاصی نیست و برای راحتتر تکرار شدن کافیست مناسبت‌ها را از کد چندبار تکرار کرد

**Comment by ebraminio** [comment]
خب راه‌حلی بالاخره پیدا کردم و مشکل حل شد، ممنونم :)

**Comment by ebraminio** [comment]
ظاهراً این راه‌حل هم مشکل را در اندروید ۵ برطرف نمی‌کند ولی در اندروید ۷.۱ به بعد که آن را آزمایش کردم مشکل را برطرف کرده، بازم بررسی می‌کنم ببینم چه می‌شود انجام داد :)
