### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Mahdimaftoon** [persian-calendar/DroidPersianCalendar#695]
سلام لطفا مشکل بسته شدن نرم افزار در پس زمینه که در رابط کاربری شیائومی به وجود میاد رو درست کنید باتشکر

**Comment by ebraminio** [comment]
سلام گرامی متأسفانه از طرف گوشی‌ست و امکاناتی برای حل آن نداریم ولی با این راه‌حل می‌توانید از طرف خودتان آن را برطرف کنید

https://github.com/persian-calendar/DroidPersianCalendar/wiki/استثنا-کردن-تقویم-جهت-اجرای-بهتر-در-اندرویدهای-جدید

ممنونم :)
