### ISSUE TITLE
آپدیت نشدن ویجت

### ISSUE THREAD

**Issue by sinasadigh** [persian-calendar/DroidPersianCalendar#707]
من گوشی اندرویدی پوکو دارم. ویجت این برنامه رو استفاده می‌کنم ولی متاسفانه ویجت آپدیت نمی‌شه. یعنی می‌بینی ویجت ۲ام ماه رو نشون می‌ده ولی ما الان توی ۵ام ماه هستیم. وقتی می‌رم داخل برنامه ویجت هم آپدیت می‌شن دیتاش.

**Comment by ebraminio** [comment]
ادغام در #661
