### ISSUE TITLE
نمایش null

### ISSUE THREAD

**Issue by Hmyizadnia** [persian-calendar/DroidPersianCalendar#716]
سلام
ضمن تشکر بابت نرم افزار بسیار خوبی که ارائه دادین
بعد از آپدیت آخر در ویجت برنامه یک نوشته null نمایش داده می شود.

**Comment by ebraminio** [comment]
سلام گرامی، کدام ویجت؟ عکسی امکان دارد تهیه کنید از این مشکل؟ ممنونم

**Comment by Hmyizadnia** [comment]
خیلی ممنون از پاسخگویی و پیگیریتون
عکس رو براتون پیوست کردم.

**Comment by ebraminio** [comment]
پیوستتون رو دریافت نکردم :/ می‌تونید در ظاهر خود گیت‌هاب اون رو قرار بدید؟ اگر مایل بودید به این ایمیل عکستون رو ارسال کنید
persian-calendar-admin@googlegroups.com

**Comment by Hmyizadnia** [comment]
![Screenshot_20210905-123106~2](https://user-images.githubusercontent.com/90126762/132121347-09a77f77-8e44-464f-ad01-5171a4295c68.jpg)

**Comment by Hmyizadnia** [comment]
اسکرین شات گرفتم، آپلود کردم.

**Comment by ebraminio** [comment]
حیف، چه اشتباهی، برطرف شد، ممنونم :) می‌توانید در تنظیمات، پیشرفته، شخصی‌سازی ویجت‌ها و اعلان، آخرین گزینه، مکان در اوقات شرعی را غیر فعال کنید را در حال حاضر غیرفعال کنید تا اشکال در نسخهٔ بعدی برطرف شود، ممنونم :)

**Comment by Hmyizadnia** [comment]
درود بر شما، خدا خیرتون بده
هم به خاطر نرم افزار خیلی خوبی که نوشتین هم به خاطر این که اینقدر خوب پشتیبانیش می کنین
سلامت و موفق باشین
