### ISSUE TITLE
مشکل چپ به راست شدن تقویم

### ISSUE THREAD

**Issue by Hmyizadnia** [persian-calendar/DroidPersianCalendar#719]
سلام
روز بخیر
من نرم افزار شما رو روی گوشی سامسونگ اس ۱۰ نصب کردم، اندرویدشم ۱۱ هست، ولی خیلی وقت ها که وارد نرم افزار میشم تقویم از چپ به راست شده‌.
مجبورم یک بار کامل نرم افزار رو ببندم دوباره باز کنم که مشکل حل بشه و تقویم از راست به چپ بشه.
زبان گوشی انگلیسی هست، نرم افزار هم آخرین ورژن نصب شده.
البته این مشکل خیلی وقت هست که وجود داره.
![IMG-20210907-WA0005](https://user-images.githubusercontent.com/90126762/132450312-ab709b14-3e34-4719-a253-427e59bbe836.jpg)

**Comment by ebraminio** [comment]
درست می‌گید، مشکل که سیستم دوباره می‌خوات زبان خودشو به برنامه اعمال کنه و راه خیلی قابل تکیه‌ای که اینطوری مشکل درست نکنه حداقل من نمی‌شناسم :/ استفاده‌تون از شیفت‌کاری راستی خیلی قشنگ بود :)

**Comment by Hmyizadnia** [comment]
بسیار ممنون و سپاسگزارم از پاسخگوییتون🙏🙏🙏

**Comment by ebraminio** [comment]
نه ایراد نداره مشکل باز باشه، به هر حال مشکل که وجود داره ولی فعلاً راه‌حل قطعی‌شو نمی‌دونیم :) اگه خیلی خیلی زیاد پیش میاد می‌تونید تنظیم گوشی‌تون رو روی فارسی قرار بدید ولی درستش که راه‌حلی پیدا کنیم، ممنونم :)

**Comment by Hmyizadnia** [comment]
ببخشید من فکر کردم کاریش نمیشه کرد موضوع رو بستم 😁
بازم ممنون، انشالله که راه حلش رو پیدا کنین مشکل برطرف بشه، نرم افزارتون خیلی عالی و کاربردی هست.

**Comment by ebraminio** [comment]
ممنونم :)

**Comment by ebraminio** [comment]
ادغام با 
#380
