### ISSUE TITLE
نمایش کلمه null جلوی ساعت اذان در ویجت

### ISSUE THREAD

**Issue by theuser17** [persian-calendar/DroidPersianCalendar#720]
در ویجت، مقابل اذان (بعد از ساعت)، متن null داخل پرانتز نمایش داده میشه!
_تست شده روی گوشی شیائومی با اندروید نسخه 11_

[تصویر نمونه](https://s19.picofile.com/file/8440466742/Screenshot_2021_09_08_10_15_08_168_com_miui_home.jpg)

**Comment by theuser17** [comment]
این مشکل حتی توی نوار نوتیف هم هست

**Comment by ebraminio** [comment]
درست می‌فرمایید، چه اشتباهی، حیف
در #716 آن را برطرف کردم
در حال حاضر می‌توانید در تنظیمات، پیشرفته، شخصی‌سازی ویجت‌ها و اعلان، آخرین گزینه، مکان در اوقات شرعی را غیر فعال کنید را در حال حاضر غیرفعال کنید تا اشکال در نسخهٔ بعدی برطرف شود، ممنونم :)
