### ISSUE TITLE
مشکل اعلانات

### ISSUE THREAD

**Issue by setayesh0968** [persian-calendar/DroidPersianCalendar#722]
عرض سلام و درود خدمت شما دوستان عزیز و ممنون بابت برنامه خوبتون
در نسخه قبل ، عدد روز ماه در قسمت اعلانات قابل مشاهده بود و بسیار کاربردی بود .
ولی از آپدیت جدید بجای تاریخ ، فقط آیکون برنامه رو نشون میده .
اگه ممکنه این مشکلو حل کنید
خیلی به دردمون میخورد
ممنون از زحمات شما
سپاسگزارم
مدل گوشی بنده شیائومی نوت ۹ پرو

**Comment by ebraminio** [comment]
تاجایی که می‌دونم این مشکل عمدی از طرف برند گوشی‌تون ایجاد شده و کاری در این رابطه از برنامه‌ها ممکن نیست :/
