### ISSUE TITLE
Question about android:configChanges=orientation

### ISSUE THREAD

**Issue by rezazarchi** [persian-calendar/DroidPersianCalendar#738]
سلام
من یه سوال در مورد 
AndroidManifest
داشتم. برای اکتیویتی اصلی برنامه 
android:configChanges=orientation
ست شده. آیا دلیل خاصی وجود داره که هنوز این مورد در پروژه وجود داره؟
این مانع از ایجاد مجدد بعضی از ویوها در زمان چرخش صفحه نمایش میشه که میتونه باعث ایجاد اشکال بشه

**Comment by ebraminio** [comment]
<div dir=rtl>درست می‌فرمایید، هنوز state برنامه در جای خاص نگه‌داری نمی‌شود که تغییر orientation باعث از بین رفتن آن نشود، برنامه‌مون فعلاً این هست که پروژه کم کم از jetpack compose استفاده که جدا کردن ظاهر برنامه از وضعیت ساده است و نگه داشتن از وضعیتی که با از بین رفتن ظاهر از بین نرود به سادگی تبدیل یک خط است مگر اینکه برنامهٔ کوتاه مدتتری به صرفه باشد، ممنون :)  
</div>
