### ISSUE TITLE
آپدیت نشدن تاریخ در ساعت 00.00

### ISSUE THREAD

**Issue by mb-real** [persian-calendar/DroidPersianCalendar#778]
سلام. برنامه وقتی ساعت از ۱۲ شب می گذرد تاریخ رو تغییر نمی دهد، و فقط زمانی تغییر می کند که به داخل برنامه رفته باشیم و در اون صورت تاریخ رو به روز میکند.

**Comment by ebraminio** [comment]
بله در نسخهٔ جدید یک دکمهٔ رفرش گذاشته‌ایم، ایده‌آل نیست ولی فعلاً راه بهتری هم نمی‌شناسیم، شرمنده که جوابی ندادم و ممنونم :)

**Comment by mb-real** [comment]
مشکل از خود اندروید و بهینه سازی باتری بود که برنامه رو اتوماتیک از حافظه خارج میکرد و باعث میشد نوتفیکیشن بار برنامه تاریخ رو به روز رسانی نکنه.

**Comment by ebraminio** [comment]
اوه ممنونم مطلعمون کردید 🙏🙏🙏
