### ISSUE TITLE
وضوح نامناسب لوگو در صفحهٔ اسپلش

### ISSUE THREAD

**Issue by ivadham** [persian-calendar/DroidPersianCalendar#783]
رزولوشن تلفن همراه من: 1920*1080

![Screenshot_20211122-123411](https://user-images.githubusercontent.com/11696957/142833861-94d8d732-57f7-4209-87d9-319cc9d6a0e9.png)

**Comment by ebraminio** [comment]
دقتتون عالی بود 👌

کمی دغدغهٔ حجم بوده و هست و که در این مورد دیگه چاره‌ای نیست و باید درستش کنیم، ممنونم :)

**Comment by ivadham** [comment]
به‌نظر می‌رسه لوگوتون با استفاده از نرم‌افزارهای طراحی وکتور ایجاد شده باشه. در نتیجه می‌شه خروجی «[اس-وی-جی](https://en.wikipedia.org/wiki/Scalable_Vector_Graphics)» گرفت و در صفحهٔ اسپلش، به‌جای «[پی-ان-جی](https://en.wikipedia.org/wiki/Portable_Network_Graphics)» ازش استفاده کرد. هم‌زمان، هم حجم کاهش پیدا می‌کنه، هم از نظر ابعاد مقیاس‌پذیر می‌شه.

البته خودم تاحالا چنین کاری نکردم، ولی احتمالاً شدنی‌ست.

**Comment by ebraminio** [comment]
با تشکر توسط @nullkit اصلاح شد :)
