### ISSUE TITLE
مقیاس نادرست خط‌کش

### ISSUE THREAD

**Issue by ivadham** [persian-calendar/DroidPersianCalendar#784]
مقیاس خط‌کش، چه در واحد سانتی‌متر، چه در واحد اینچ صحیح نیست.

- تصویر سمت راست: تقویم فارسی
- تصویر سمت چپ: [مژر](https://github.com/JoelBryceAnderson/Measure)

![Screenshot_20211122-134011](https://user-images.githubusercontent.com/11696957/142846384-cea71d71-ee33-4c99-9d25-152dc0afc0f5.png)

**Comment by ebraminio** [comment]
درست می‌فرمایید
https://stackoverflow.com/a/23476122
حالت فعلی میانگین طول و عرض است ولی اطلاعات دقیقتری در افقی و عمدی هم ارائه می‌شود

کاش یکی دو روز زودتر این موضوع را متوجه می‌شدیم :) البته در صحت عملکرد برنامه از اول وجود نداشته ولی آن را از ویژگی‌های نسخهٔ جدید برداشتم که توقع بیشتری ایجاد نکند تا در نسخهٔ بعد آن را اصلاح کنیم، ممنونم :)
