### ISSUE TITLE
باگ شفاف بودن دیالوگ‌های برنامه در نسخه ۷.۱.۱

### ISSUE THREAD

**Issue by lonelyglitch** [persian-calendar/DroidPersianCalendar#786]
در نسخه ۷.۱.۱ پنجره‌های دیالوگ برنامه در تنظیمات به صورت شفاف هستند که وضوح و قابلیت خواندن متن‌ها رو کاهش می‌ده.

**Comment by ebraminio** [comment]
اندرویدتان چند است، عکسی تهیه می‌فرمایید؟ ممنونم :)

**Comment by lonelyglitch** [comment]
اندروید ۱۲، در ضمن این اتفاق بر روی همه‌ی پوسته‌های برنامه می‌افتد.
![Screenshot_20211123-112845_Persian Calendar](https://user-images.githubusercontent.com/76869222/142988314-6a6f6616-a645-4045-94b6-eba2f3b64f9d.png)
