### ISSUE TITLE
مشکل در بروز رسانی notification 

### ISSUE THREAD

**Issue by Homayoonet** [persian-calendar/DroidPersianCalendar#788]
سلام،
من اندروید ۹ دارم و گوشیم روت شده نیست، هر چند این مشکلات رو با گوشی روت شده هم داشتم. خیلی اوقات عددی که در notification bar به عنوان تاریخ نمایش داده میشه آپدیت نمیشه و مجبورم وارد برنامه بشم تا اون عدد آپدیت بشه.
همچنین گاهی اوقات کلا اون عدد و نمایش تاریخ در صفحه لاک اسکرین کلا می روند و چیزی نمایش داده نمیشه حتی وارد اپ هم میشم باز هم نمیان و مجبورم برنامه رو حذف و نصب کنم.

**Comment by ebraminio** [comment]
سلام، 

https://github.com/persian-calendar/DroidPersianCalendar/wiki/استثنا-کردن-تقویم-جهت-اجرای-بهتر-در-اندرویدهای-جدید

این راهنما بررسی کنید شاید اوضاع را کمی بهتر کند، ممنون :)

**Comment by Homayoonet** [comment]
سلام مجدد، مشکلم برطرف شد. سپاس فراوان

**Comment by ebraminio** [comment]
ممنونم :)

**Comment by masoud2005** [comment]
سلام من میخوام هک فیسبوک یاد بگیرم میشه یکی کد های  هک فیسبوک واسم بدید خیلی ممنون 


Hi, I want to learn facebook hack can you give me one facebook hack code thank you very much
