### ISSUE TITLE
قطب نما/:

### ISSUE THREAD

**Issue by pouria123123** [persian-calendar/DroidPersianCalendar#790]
اقا بخش قطب نما مشکل داره رو گوشی شیائومی وقتی واردش میشیم میگه
 مثل اینکه دسگاه شما سنسور قطب نما نداره
:) الان میخام وسط بیابون نماز بخونم کی پاسخگوه
ممنون میشم پاسخ بدید

Xiaomi redmi note 10 android 11 miui 12.5.4
And v 7.1.2 of Persian calendar

**Comment by ebraminio** [comment]
سلام گرامی در نسخهٔ بعد این قضیه بهبود پیدا می‌کنه فقط تلگرام دارید یک بررسی نهایی کنیم؟ ممنونم :)
