### ISSUE TITLE
Widgets are not transparent anymore on Samsung OneUI 4 (Android 12)

### ISSUE THREAD

**Issue by gnome1919** [persian-calendar/DroidPersianCalendar#793]

**Comment by ebraminio** [comment]
ممنونم بابت اطلاع‌رسانی گرامی، اگر theme را از پیش‌فرض دستگاه تغییر دهید درست می‌شود ولی برای نسخهٔ بعد آن را دارای گزینه کرده‌ام ممنونم :)

**Comment by gnome1919** [comment]
با سپاس،
متوجه نشدم، themes پیش‌فرض دستگاه هست، دقیقا چه تعبیری باید بدم؟

**Comment by ebraminio** [comment]
اگر theme برنامه به هر چیزی به جز theme پیش‌فرض دستگاه تغییر دهید ویجت دیگر رنگ‌آمیزی سیستم را در رابطه با ویجت‌ها دنبال نمی‌کند، اگر مشکلی وجود داشت حتماً بفرمایید :)

**Comment by gnome1919** [comment]
درسته، ولی من هیچ چیزی رو در قسمت theme دستگاه تغییر ندادم

**Comment by ebraminio** [comment]
در نسخهٔ بعد مشکلش را برطرف می‌کنم، اگر مایل بودید اگر آی‌دی تلگرامتان را محبت کنید می‌توانم برایتان جهت آزمایش بفرستم، ممنون :)

**Comment by gnome1919** [comment]
بله حتما، خواهش میکنم، خوشحال میشم کمکی بکنم.

Telegram: @Ghavanini
