### ISSUE TITLE
Creating Sevice and Content Provider

### ISSUE THREAD

**Issue by omidp** [persian-calendar/DroidPersianCalendar#8]
it might be a good idea to create a content provider to extend and interact with other android programs so people can improve and add new services based on this app like task management

**Comment by ebraminio** [comment]
امید جان پیشنهاد خیلی جالبی داده بودید آن زمان! بگم دلیل اینکه دنبال همچین چیزی نبودم یه مقداری این بوده که بلد نبودنمم و البته الآنم نیستم :)
