### ISSUE TITLE
Widgets are not transparent after v7.0 (A12) 

### ISSUE THREAD

**Issue by Generator20** [persian-calendar/DroidPersianCalendar#823]
متاسفانه قابلیت شفاف شدن پس زمینه ویجت های اپلیکیشن پس از ورژن 7.0 دست‌کم در اندروید 12 از کار افتاده است و در تنظیمات نیز گزینه تغییرات رنگ پس زمینه حذف شده است.

Application's widgets are not transparent anymore.(Tested on Android 12)

**Comment by ebraminio** [comment]
سلام گرامی یک گزینه‌ای دارد به اسم «پیروی از رنگ‌بندی سیستم در ویجت‌ها» آن را بزنید دیگر می‌توانید به صورت دلخواه تنظیم کنید :)

**Comment by Generator20** [comment]
درود بر شما
حق با شماست، بنده به یکی دو ورژن اخیر با این پیشفرض که مشکل همچنان به قوت خود باقیست بروزرسانی نکردم از این جهت از رفعِ باگ اطلاع نداشتم و عذرخواهی میکنم از این بابت. بینهایت سپاسگزارم از اپلیکیشن مفید و ارزشمندتون

**Comment by ebraminio** [comment]
ممنونم گرامی :)
