### ISSUE TITLE
Chinese considerations

### ISSUE THREAD

**Issue by szescxz** [persian-calendar/DroidPersianCalendar#851]
Chinese translator here, and I'd like to report some issues that prevent me from providing a good translation.

### Short form of day-of-week
Right now, I think the current code simply use the first character of the long form of day-of-week names, which works well for English and also Japanese:
![](https://user-images.githubusercontent.com/49463229/152099116-cd8c555b-488b-4f3b-9447-b5408df37607.jpg)
However, long names in Chinese all begin with `星`, so... (we take the last character instead, so the expected translation is `日` (Sunday), `一`, `二`, `三`, `四`, `五` and `六`)
![](https://user-images.githubusercontent.com/49463229/152099340-c70c740c-4467-41c4-97a1-3e40850ac648.jpg)
Please consider to make these strings available for translate so translators can decide themselves.

### Shared strings
I think the translation for the ` and ` string is shared between the titles in Settings:
![](https://user-images.githubusercontent.com/49463229/152099855-de951eda-2543-4510-b87a-9f9e5ef5b4f7.jpg)
... and the distance between dates (countdown/countups):
![](https://user-images.githubusercontent.com/49463229/152100149-87c21aeb-7910-4e14-9965-2de1e6e7a0f7.jpg)
In Chinese, we prefer not have the ` and ` word in second case, or (if it cannot be an empty string) use `和` for the first case and `又` for the second.

### Some details that's currently not controllable by translators
Reusing this screenshot again:
![](https://user-images.githubusercontent.com/49463229/152099340-c70c740c-4467-41c4-97a1-3e40850ac648.jpg)
The overall design of the app appears to use "DD-MM-YYYY" format for all non-numerical dates. But in Chinese we prefer "YYYY-MM-DD". So in this example, instead of `二月 2022` (February 2022), I prefer `2022 二月` (2022 February), or better `2022年1月` (adding the "year" word and use short-form of month names). _This only applies to the Gregorian calendar; to make life more easier for end-user's Iranian friends, I decided to keep the Persian month names untranslated, so Persian calendar can keep its current format._
This one probably need some code refactoring, so it's OK if not possible to implement. The following one is an easier example (all datetimes are hardcoded in "HH:MM, DD MM YYYY" format; we prefer something like "YYYY MM DD HH:MM"):
![](https://user-images.githubusercontent.com/49463229/152102116-76160c0e-4982-4937-89b8-8a9636dcf035.jpg)
Or maybe just use some standard l10n libraries instead. :)

![](https://user-images.githubusercontent.com/49463229/152101784-e437c887-7ee9-423b-addb-27468ff8ff3b.jpg)
This is an easy one: the brackets `()` of `Wednesday (Iran Time)` are half-width characters, and in Chinese we prefer full-width characters `（）`.

There are probably more examples; I'll try to append them to this issue if found.
Again, thanks for developing this great app!

**Comment by ebraminio** [comment]
Thanks a lot for this! I wanted to implement Chinese calendar, even years before #824 as some local Iranian users wanted to see correct original animal years of Chinese calendar instead our tweaked one. For that I need an implementation of Chinese date to JDN and vice versa in https://github.com/persian-calendar/calendar

> However, long names in Chinese all begin with 星, so... (we take the last character instead, so the expected translation is 日 (Sunday), 一, 二, 三, 四, 五 and 六)

Fixed the first one, feel free to verify from the below picture :)

<img width="344" alt="image" src="https://user-images.githubusercontent.com/833473/152117142-cc3a6412-f365-444c-b230-c9dae27a2d57.png">

> In Chinese, we prefer not have the and word in second case, or (if it cannot be an empty string) use 和 for the first case and 又 for the second.

Assuming Japanese also has the same need, did the same for Japanese also, feel free to verify from the below picture :)

<img width="339" alt="image" src="https://user-images.githubusercontent.com/833473/152121046-4863f4df-9d20-4297-824f-3c1671715dfa.png">

> The overall design of the app appears to use "DD-MM-YYYY" format for all non-numerical dates. But in Chinese we prefer "YYYY-MM-DD". So in this example, instead of 二月 2022 (February 2022), I prefer 2022 二月 (2022 February), ...

Fortunately I have a bit of infrastructure to handle this already, did the same for Japanese also, feel free to verify from below screenshot :)

<img width="338" alt="image" src="https://user-images.githubusercontent.com/833473/152123965-c81edc0b-62e3-4817-8c08-c5b73c02fbcd.png">

> or better 2022年1月 (adding the "year" word and use short-form of month names).

Guess I have to defer this but it isn't impossible also :)

> This only applies to the Gregorian calendar; to make life more easier for end-user's Iranian friends, I decided to keep the Persian month names untranslated, so Persian calendar can keep its current format.

Special casing other calendars here is a bit tedious :/ Feel free to translate those as well I'd say :)

> This one probably need some code refactoring, so it's OK if not possible to implement. The following one is an easier example (all datetimes are hardcoded in "HH:MM, DD MM YYYY" format; we prefer something like "YYYY MM DD HH:MM"):

Done the same for Japanese,

<img width="338" alt="image" src="https://user-images.githubusercontent.com/833473/152125851-f41eeccd-56c8-4bf7-8d97-d84721d4a302.png">

> Or maybe just use some standard l10n libraries instead. :)

I'm supporting languages officially not supported by Android and having to support dates aren't by l10n libraries :/ I can't bundle ICU as it takes too much of space from the resulting APK and can't use Android provided ICU either as that is minApi 24 and we are in minApi 17 :/

> This is an easy one: the brackets () of Wednesday (Iran Time) are half-width characters, and in Chinese we prefer full-width characters （）.

Fixed this one as well :)

<img width="338" alt="image" src="https://user-images.githubusercontent.com/833473/152127336-eab56640-c2f7-4908-bd6f-5d967701c351.png">

> There are probably more examples; I'll try to append them to this issue if found.

Feel free to do so :)

> Again, thanks for developing this great app!

Thank _you_! Added you to the credits also :) Do you any IM platform I can reach to you maybe? Thanks :)

**Comment by ebraminio** [comment]
> I'm currently wondering whether I should apply this [typewriting guideline](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.en.md) to this project.

I understand and like manual of styles generally :) 

>  This guideline requires a half-width space is required between numbers and Chinese characters.

In Persian (somehow unlike most of other Arabic script written languages) we have a zero space character suggested in manual of style so I feel what you mean :) Feel free to apply suggest where that should be needed.

> This one does not seem to be implemented correctly (wrong screenshot)? I'm expecting 2022 on the left (or top, depending on secondary calendar settings) of 二月.

Oh, right, it is fixed already

<img width="340" alt="image" src="https://user-images.githubusercontent.com/833473/153655169-d2383341-3c26-4305-9a33-7b73f69445b3.png">

On swapping top and bottom when secondary isn't enabled, it is more about having the more frequently changing one on top so a bit reluctant here.

> The problem is that I don't think we have official Chinese translation for them, and in my opinion it's also inappropriate to translate them to something like "1st Month", "2nd Month", "12th Month" etc.

Understandable.

> The correct form for this is YYYY 年 M 月 D 日 H:MM (M, D and H are usually not zero-padded; all format codes are replaced with numbers). If it's 12-hour format, add 上午 for AM or 下午 for PM after the date but before the time (e.g. 2022 年 2 月 9 日上午 8:00).

Guess except the month one now matches better with your expectation :)

<img width="338" alt="image" src="https://user-images.githubusercontent.com/833473/153659575-6e945e56-3daf-4439-889a-388c519056f7.png">

and

<img width="340" alt="image" src="https://user-images.githubusercontent.com/833473/153659599-2191d9a1-6ecb-4fc6-bb89-e9ab3232ff01.png">

> Also one thing: I noticed that the fallback language for app title and description on Google Play is currently Persian. Is that intended? (because usually I expect it fallbacks to English for an app with i18n support)

I just have set Persian as the default language which apparently means fallback one also, I wanted to make English as the main language just now but it now doesn't like having 'free' as in 'free software' term I was using in the description and now needs English phone screenshots I don't have right now :/

**Comment by szescxz** [comment]
> In Persian (somehow unlike most of other Arabic script written languages) we have a zero space character suggested in manual of style so I feel what you mean :) Feel free to suggest where that is needed.

So far the only part I cannot fix myself is the countdown part (whitespace needed before `6` and `13` in the screenshot):
![](https://user-images.githubusercontent.com/49463229/155077992-686f61a2-c016-460e-ad6d-2bf2b552b7d5.png)

> On swapping top and bottom when secondary isn't enabled, it is more about having the more frequently changing one on top so a bit reluctant here.

Right, maybe just keep the current implementation.

> Guess except the month one now matches better with your expectation :)

Checked the Persian calendar implementation in Google Calendar, they seem to translate month names exactly as "1st Month", "12th Month" etc., so I gave up and follow that instead (also fixes this problem for now). _On a side note, they use transliteration for that in Islamic calendar. 😂_

After this change, I'd suggest adding a `年` after the year numbers (so it becomes `1402 年 10 月`, `2023 年 12 月-2024 年 1 月` in the screenshot, respectively):
![](https://user-images.githubusercontent.com/49463229/155079547-48f682f7-0c85-409c-b00d-3cc918457b92.jpg)

One more thing, I guess you'd want to add a LRM control character (probably with some formatting adjustments) here in events, likely for all LTR languages:
![](https://user-images.githubusercontent.com/49463229/155081091-76ccb714-e22d-45ec-acdc-33996b82fb0b.png)

==========

Since most of the fundamental issues were solved, I'm closing this issue for now, and re-open later when I find more issues.

**Comment by ebraminio** [comment]
> So far the only part I cannot fix myself is the countdown part (whitespace needed before 6 and 13 in the screenshot), due to Weblate enforcing the trailing whitespace fixup:

Hopefully now looks better :)

<img alt="image" src="https://user-images.githubusercontent.com/833473/155230922-1e51ae91-015a-4667-b304-232a94377256.png">

But I think I have problem on writing half width space, which message you have used it so I can copy from it?

> Checked the Persian calendar implementation in Google Calendar, they seem to translate month names exactly as "1st Month", "12th Month" etc., so I gave up and follow that instead (also fixes this problem for now). On a side note, they use transliteration for that in Islamic calendar. 😂

Right 😄 After all these years it still misses essential features for an actual i18n is missing there and the main calendar can't be changed.

> After this change, I'd suggest adding a 年 after the year numbers (so it becomes 1402 年 10 月, 2023 年 12 月-2024 年 1 月 in the screenshot, respectively):

Hopefully looks better now :)

<img alt="image" src="https://user-images.githubusercontent.com/833473/155232192-eea92e1c-586e-4b76-a4c6-28ecbbb3ea06.png">

> Maybe use abbreviations, e.g. FOSS (Free and Open-Source Software). 😜

Exactly 😁 Thanks for reminding me, I changed its default language and used "foss" on the title.

> One more thing, I guess you'd want to add a LRM control character (probably with some formatting adjustments) here in events, likely for all LTR languages:

didn't work with one LRM :/ I should investigate more

> Since most of the fundamental issues were solved, I'm closing this issue for now, and re-open later when I find more issues.

What I really miss is a Chinese calendar though, hopefully I can reach to that soon 😊

**Comment by szescxz** [comment]
> But I think I have problem on writing half width space, which message you have used it so I can copy from it?

If you mean which whitespace character to use, Western word space (` `) is okay (or U+0020 if you want to be exact).

> What I really miss is a Chinese calendar though, hopefully I can reach to that soon 😊

Good luck on that! Also I'm seeing you adding Nepali calendar support, which calendar exactly? (as I see two calendars on https://en.wikipedia.org/wiki/Nepali_calendar)

**Comment by ebraminio** [comment]
> Good luck on that! Also I'm seeing you adding Nepali calendar support, which calendar exactly? (as I see two calendars on https://en.wikipedia.org/wiki/Nepali_calendar)

I thinks ours is Vikram Samvat https://en.wikipedia.org/wiki/Vikram_Samvat Now I see I should've done the naming better :/ And guess that second one also is needed.
