### ISSUE TITLE
اضافه کردن زبان لری به برنامه تقویم فارسی

### ISSUE THREAD

**Issue by hosseinabaspanah** [persian-calendar/DroidPersianCalendar#859]
لطفا زبان لری رو به برنامه اضافه کنید...
برای ترجمه زبان لری من  با کمک اعضای فرهنگستان زبان لری میتونم کار ترجمه این برنامه رو انجام بدم...
راه های ارتباطی با من برای ترجمه تقویم فارسی به زبان لری:::
09017145908
t.me/hosseinabaspanah

**Comment by ebraminio** [comment]
برای شروع ترجمه می‌توانید از همین الآن در اینجا مشغول به انجام شوید https://hosted.weblate.org/engage/persian-calendar

ولی برای نمایش در نسخهٔ نهایی در این برنامه تقریباً فقط یک شرط را برای افزودن زبان‌های داخل ایران قرار داده‌ایم و آن اینکه به سندی یا جایی رسمی  نیاز است که نمایانگر استفاده از زبان و خط آن در دولت ایران و استفاده از آن خط وجود دارد باشد چرا که کار استفاده از آن خط و زبان ابتکاری از سوی این پروژه نشود و توافقی رسمی و بیرون از پروژه به خصوص از طرف رسانه‌ای رسمی در دولت یا مجله‌ای یا کتابی دارای مجوز در ایران وجود داشته باشد. در صفحهٔ درباره، قسمت «نام ماه‌ها و زبان‌ها»، خط آخر، آنچه که اشاره می‌کنم برای زبان‌های مختلفی که آورده شده را با مثال آورده‌ام.

این فایل را می‌بندم ولی ادامه گفتگو را همینجا می‌توانیم داشته باشیم، ممنون :)

**Comment by ebraminio** [comment]
دکمه ایجاد زبانی جدید زیر همان فهرست زبان‌هاست در همان سایت است

**Comment by hosseinabaspanah** [comment]
چرا موقع اضافه کردن پروژه زبان جدید ازم هاست رایگان و پولی میخواد؟؟؟
اگه ممکنه آموزش تصویری تعریف زبان جدید رو برام بفرستین...

در تاریخ سه‌شنبه ۸ فوریهٔ ۲۰۲۲،‏ ۲۲:۱۵ ebraminio ***@***.***>
نوشت:

**Comment by ebraminio** [comment]
ظاهراً جای اشتباهی رفته بودید و حق دارید کمی ظاهرش تغییر کرده انگار، آنچه که می‌خواستید اینجاست https://hosted.weblate.org/new-lang/persian-calendar/persian-calendar ولی آنجا هم لری نداشت، لری که مد نظرتان هست چه کد زبانی‌ی دارد؟ https://en.wikipedia.org/wiki/Luri_language اینجا کدهای زبانی لری‌های مختلف را آورده، lrc یا bqi یا luz؟

**Comment by hosseinabaspanah** [comment]
در صورتی که امکان دارد هر سه کد زبان لری را تعریف کنید تا برای ترجمه هر سه
شاخه از زبان لری در آینده نیاز به ایمیل زدن نباشد...
با توجه به استرینگ های برنامه برای ترجمه هر زبان؛فکر کنم جمعا برای سه شاخه
از زبان لری در کم تر از سه ماه بتوانم آن ها را ترجمه کنم...

‫‪ebraminio‬‏ ***@***.***‬‏> در تاریخ چهارشنبه ۹ فوریه ۲۰۲۲
ساعت ۱۹:۳۶ نوشت:‬

**Comment by ebraminio** [comment]
هر سه را اضافه کردم که اینجا قابل مشاهده است https://hosted.weblate.org/projects/persian-calendar/persian-calendar/#translations فقط توجه کنید آن شرط اولیه که نشان داده شود استفاده از خط برای این زبان ابتکاری از شما و این پروژه نیست و رسانه‌ای رسمی از طرف دولت ایران چنین کاری را کرده است برای افزوده شدن به نسخهٔ نهایی اهمیت قطعی دارد. ممنون :)

**Comment by hosseinabaspanah** [comment]
دستتون دردنکنه...
حتما برای رسمی شدنش مدرک رسمی از دولت ایران براتون میفرستم...
فقط برای فرستادن مدارک در آینده اشکال نداره تو همین ایمیل بهتون اطلاع بدم؟؟؟

در تاریخ پنجشنبه ۱۰ فوریهٔ ۲۰۲۲،‏ ۱۳:۴۸ ebraminio ***@***.***>
نوشت:

**Comment by hosseinabaspanah** [comment]
ببخشید میخواستم بپرسم باید تو تعریف ترجمه ها از خط لری بر اساس عربی استفاده
کنم یا خط لری که بر اساس لاتین هست؟؟؟
و اینکه اگه قابل تغییر هست تو کدوم قسمت باید تعریف بشه؟؟؟

در تاریخ پنجشنبه ۱۰ فوریهٔ ۲۰۲۲،‏ ۱۳:۴۸ ebraminio ***@***.***>
نوشت:

**Comment by ebraminio** [comment]
دربارهٔ خط عربی یا لاتین، کدام یک به شکل رسمی در آن مدارکی که دارید استفاده شده است؟ آن‌ها جایی عمومی در حال حاضر وجود نداشتنه‌اند؟ اگر نه می‌ترسم کم کم به حوزه‌ای وارد شویم که در رابطه با زبان ابتکاری باشد و از حوصلهٔ این برنامه خارج شود.

**Comment by hosseinabaspanah** [comment]
خیر اینجور نیست...ما چون دو خط داریم خواستم بپرسم که از کدوم خط باید
استفاده کنیم...
من از همون خط بر پایه عربی استفاده میکنم مشکلی نداره...
دستتون دردنکنه بابت راهنماییتون...

در تاریخ پنجشنبه ۱۰ فوریهٔ ۲۰۲۲،‏ ۱۵:۲۹ ebraminio ***@***.***>
نوشت:
